// Service worker — GENERATED by tools/build-sw.rb from tools/sw.template.js. Don't edit sw.js directly.
// Strategy: precache every app file under a content-hashed version; serve from cache first
// (fast + offline). A new deploy = new hash = new worker, and the app offers a "Refresh".
const CACHE_VERSION = 'cc-fc153388efab';
const PRECACHE = [
  './',
  './assets/icons/apple-touch-icon.png',
  './assets/icons/favicon-32.png',
  './assets/icons/icon-192.png',
  './assets/icons/icon-512.png',
  './assets/icons/icon-maskable-512.png',
  './assets/icons/icon-maskable.svg',
  './assets/icons/icon.svg',
  './content/bootcamp.js',
  './content/course.js',
  './content/game.js',
  './content/lectures/l01.js',
  './content/lectures/l02.js',
  './content/lectures/l03.js',
  './content/lectures/l04.js',
  './content/lectures/l05.js',
  './content/lectures/l06.js',
  './content/lectures/l07.js',
  './content/lectures/l08.js',
  './content/lectures/l09.js',
  './content/lectures/l10.js',
  './content/messages.js',
  './content/nursing.js',
  './content/reactions.js',
  './content/words.js',
  './css/app.css',
  './index.html',
  './js/app.js',
  './js/chem/analyze.js',
  './js/chem/condensed.js',
  './js/chem/generator.js',
  './js/chem/graph.js',
  './js/chem/layout.js',
  './js/chem/namecheck.js',
  './js/chem/nameparse.js',
  './js/chem/namer.js',
  './js/chem/reactions.js',
  './js/chem/render.js',
  './js/chem/smiles.js',
  './js/cloud/codec.js',
  './js/cloud/config.js',
  './js/cloud/fake.js',
  './js/cloud/firebase.js',
  './js/cloud/gate.js',
  './js/cloud/index.js',
  './js/cloud/sync.js',
  './js/game/decks.js',
  './js/game/draw.js',
  './js/game/engine.js',
  './js/game/sound.js',
  './js/game/words.js',
  './js/lib/markup.js',
  './js/lib/random.js',
  './js/quiz/bank.js',
  './js/quiz/checkers.js',
  './js/quiz/gen/acidbase.js',
  './js/quiz/gen/common.js',
  './js/quiz/gen/properties.js',
  './js/quiz/gen/reactions.js',
  './js/quiz/gen/structure.js',
  './js/quiz/generators.js',
  './js/quiz/session.js',
  './js/router.js',
  './js/routes.js',
  './js/state/feedback.js',
  './js/state/game.js',
  './js/state/milestones.js',
  './js/state/progress.js',
  './js/state/srs.js',
  './js/state/store.js',
  './js/state/words.js',
  './js/ui/account.js',
  './js/ui/components.js',
  './js/ui/confused.js',
  './js/ui/dom.js',
  './js/ui/gate.js',
  './js/ui/question.js',
  './js/version.js',
  './js/views/about.js',
  './js/views/bootcamp.js',
  './js/views/cards.js',
  './js/views/exams.js',
  './js/views/game.js',
  './js/views/gameplay.js',
  './js/views/games.js',
  './js/views/home.js',
  './js/views/lab.js',
  './js/views/learn.js',
  './js/views/mistakes.js',
  './js/views/more.js',
  './js/views/notfound.js',
  './js/views/onboarding.js',
  './js/views/practice.js',
  './js/views/progress.js',
  './js/views/quiz.js',
  './js/views/reactions.js',
  './js/views/reference.js',
  './js/views/results.js',
  './js/views/settings.js',
  './js/views/tools.js',
  './js/views/words.js',
  './manifest.webmanifest',
];

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE_VERSION).then((cache) => cache.addAll(PRECACHE)));
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k.startsWith('cc-') && k !== CACHE_VERSION).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  // Our own files, plus Google's sign-in library (versioned URLs that never change), so a
  // signed-in app still opens offline. Everything else (e.g. the database) goes straight out.
  const firebaseSdk = url.hostname === 'www.gstatic.com' && url.pathname.startsWith('/firebasejs/');
  if (url.origin !== self.location.origin && !firebaseSdk) return;
  event.respondWith((async () => {
    const cache = await caches.open(CACHE_VERSION);
    if (req.mode === 'navigate') {
      // Pages: try the network (so updates are noticed), fall back to the cached app shell offline.
      try {
        const fresh = await fetch(req);
        return fresh;
      } catch {
        return (await cache.match('./index.html')) || (await cache.match('./')) || Response.error();
      }
    }
    const hit = await cache.match(req, { ignoreSearch: true });
    if (hit) return hit;
    try {
      const res = await fetch(req);
      if (res.ok && (res.type === 'basic' || (firebaseSdk && res.type === 'cors'))) cache.put(req, res.clone());
      return res;
    } catch {
      return Response.error();
    }
  })());
});
