// Lecture 3 — Alkanes (Smith Ch. 12.1–12.5)
export default {
  id: 'l03',
  number: 3,
  title: 'Alkanes',
  subtitle: 'Isomers, classifying carbons & IUPAC naming',
  chapter: 'Ch. 12.1–12.5',
  tested: true,
  summary: 'The naming system you learn here is reused for every family in the course — master the longest chain, numbering and alphabetizing rules once and they pay off all semester.',
  skills: [
    { id: 'l03.formulas', title: 'Alkane formulas', desc: 'CₙH₂ₙ₊₂ for acyclic alkanes, CₙH₂ₙ for cycloalkanes.' },
    { id: 'l03.names-1-10', title: 'Chain names 1–10', desc: 'Meth, eth, prop, but, pent, hex, hept, oct, non, dec.' },
    { id: 'l03.isomers', title: 'Constitutional isomers', desc: 'Same formula, different connections — vs. the same compound drawn differently.' },
    { id: 'l03.carbon-class', title: 'Classifying carbons', desc: '1°, 2°, 3°, 4° carbons.' },
    { id: 'l03.naming', title: 'Naming alkanes', desc: 'Longest chain, lowest numbers, alphabetical order.' },
    { id: 'l03.drawing', title: 'Drawing from a name', desc: 'Turn a name like 5-ethyl-2,6-dimethyloctane into a structure.' },
  ],
  sections: [
    {
      id: 'intro',
      title: 'Alkanes and cycloalkanes',
      minutes: 4,
      blocks: [
        { t: 'p', text: '**Alkanes** are hydrocarbons with only **C–C and C–H single bonds**. All alkane names end in **-ane**.' },
        {
          t: 'compare', items: [
            { title: 'Acyclic alkanes: $C_nH_{2n+2}$', text: 'Chains, no rings. **Saturated** — the maximum number of H atoms per C. Example: $C_5H_{12}$.' },
            { title: 'Cycloalkanes: $C_nH_{2n}$', text: 'Carbons joined in a ring. Closing the ring costs 2 H. Example: cyclohexane $C_6H_{12}$.' },
          ],
        },
        { t: 'mols', items: [{ smiles: 'CCCCC', caption: 'pentane, $C_5H_{12}$' }, { smiles: 'C1CCCC1', caption: 'cyclopentane, $C_5H_{10}$' }, { smiles: 'C1CCCCC1', caption: 'cyclohexane, $C_6H_{12}$' }] },
      ],
    },
    {
      id: 'names',
      title: 'The first ten straight-chain alkanes',
      minutes: 6,
      blocks: [
        {
          t: 'table', head: ['# C', 'Name', 'Condensed', '# C', 'Name', 'Condensed'],
          rows: [
            ['1', '**meth**ane', '$CH_4$', '6', '**hex**ane', '$CH_3(CH_2)_4CH_3$'],
            ['2', '**eth**ane', '$CH_3CH_3$', '7', '**hept**ane', '$CH_3(CH_2)_5CH_3$'],
            ['3', '**prop**ane', '$CH_3CH_2CH_3$', '8', '**oct**ane', '$CH_3(CH_2)_6CH_3$'],
            ['4', '**but**ane', '$CH_3CH_2CH_2CH_3$', '9', '**non**ane', '$CH_3(CH_2)_7CH_3$'],
            ['5', '**pent**ane', '$CH_3(CH_2)_3CH_3$', '10', '**dec**ane', '$CH_3(CH_2)_8CH_3$'],
          ],
        },
        { t: 'callout', kind: 'memory', title: 'Memory trick for 1–4', text: '"**M**onkeys **E**at **P**eanut **B**utter" → **m**eth, **e**th, **p**rop, **b**ut. From 5 on the prefixes are the Greek/Latin numbers you already know: **pent**agon (5), **hex**agon (6), **oct**opus (8), **dec**ade (10). Hept (7) and non (9) are the odd ones out — hept = "heptathlon".' },
        { t: 'callout', kind: 'tip', title: 'Bends don\'t matter', text: 'A chain drawn zig-zag, bent around a corner, or straight is still the same compound. Only **how atoms are connected** matters.' },
        {
          t: 'check', q: {
            id: 'l03-c-oct', skill: 'l03.names-1-10', type: 'num', prompt: 'How many carbons are in oct**ane**?', answer: 8, tol: 0,
            explain: 'Oct = 8 (octopus has 8 arms).',
          },
        },
      ],
    },
    {
      id: 'isomers',
      title: 'Constitutional isomers',
      minutes: 6,
      blocks: [
        { t: 'p', text: '**Isomers** are different compounds with the **same molecular formula**. **Constitutional isomers** differ in the way their atoms are **connected**.' },
        { t: 'mols', items: [{ smiles: 'CCCC', caption: 'butane $C_4H_{10}$ (straight chain)' }, { smiles: 'CC(C)C', caption: 'isobutane $C_4H_{10}$ (branched)' }] },
        { t: 'p', text: 'Isomers don\'t have to be in the same family: ethanol and dimethyl ether are both $C_2H_6O$.' },
        { t: 'mols', items: [{ smiles: 'CCO', caption: 'ethanol $C_2H_6O$' }, { smiles: 'COC', caption: 'dimethyl ether $C_2H_6O$' }] },
        { t: 'p', text: 'As the number of carbons grows, the number of isomers explodes. Pentane ($C_5H_{12}$) has **three** isomers:' },
        { t: 'mols', items: [{ smiles: 'CCCCC', caption: 'pentane' }, { smiles: 'CC(C)CC', caption: '2-methylbutane' }, { smiles: 'CC(C)(C)C', caption: '2,2-dimethylpropane' }] },
        { t: 'callout', kind: 'warn', title: 'Trap: same compound, drawn differently', text: 'Before calling two drawings isomers, **name both** (or count the longest chain and branches). If they get the same name, they are the **same compound**.' },
      ],
    },
    {
      id: 'classify',
      title: 'Classifying carbons: 1°, 2°, 3°, 4°',
      minutes: 5,
      blocks: [
        { t: 'p', text: 'Classify a carbon by counting **how many other carbons** are bonded to it. (Ignore hydrogens and everything else.)' },
        {
          t: 'table', head: ['Class', 'Bonded to', 'Typical look'],
          rows: [['**1° primary**', '1 carbon', '$CH_3$ at a chain end'], ['**2° secondary**', '2 carbons', '$CH_2$ in a chain'], ['**3° tertiary**', '3 carbons', 'CH at a branch point'], ['**4° quaternary**', '4 carbons', 'C with no H']],
        },
        {
          t: 'example', title: 'Practice from class', prompt: 'Count the 1°, 2°, 3° and 4° carbons in 5-ethyl-2,4-dimethyloctane.',
          mol: { smiles: 'CC(C)CC(C)C(CC)CCC', mode: 'condensed' },
          steps: ['Every chain end ($CH_3$) is **1°**: there are 5.', '$CH_2$ carbons inside chains are **2°**: 4.', 'Branch-point CH carbons are **3°**: 3.', 'No carbon has four carbon neighbours → 0 **4°**.'],
          answer: '1°: 5 · 2°: 4 · 3°: 3 · 4°: 0',
        },
        { t: 'callout', kind: 'life', title: 'Why this matters later', text: 'The same 1°/2°/3° idea classifies **alcohols** (Lecture 5) and **alkyl halides** (Lecture 6), and it decides how alcohols **oxidize**.' },
      ],
    },
    {
      id: 'iupac',
      title: 'How IUPAC names are built',
      minutes: 5,
      blocks: [
        { t: 'p', text: 'IUPAC (International Union of Pure and Applied Chemistry) gives every compound one unique name with three parts:' },
        {
          t: 'table', head: ['Prefix', '+ Parent', '+ Suffix'],
          rows: [['identity, location and number of **substituents** (branches)', 'number of C in the **longest chain**', 'the **functional group** (-ane for alkanes)']],
        },
        { t: 'h', text: 'Substituent (branch) names' },
        { t: 'p', text: 'A branch is named by changing **-ane to -yl**:' },
        {
          t: 'table', head: ['Branch', 'Name', 'Branch', 'Name'],
          rows: [['$CH_3$–', '**methyl**', '$CH_3CH_2CH_2CH_2$–', '**butyl**'], ['$CH_3CH_2$–', '**ethyl**', '$CH_3(CH_2)_4$–', '**pentyl**'], ['$CH_3CH_2CH_2$–', '**propyl**', '$(CH_3)_2CH$–', '**isopropyl** (1-methylethyl)']],
        },
        { t: 'h', text: 'Drug names' },
        { t: 'p', text: 'Most drugs have three names: a **systematic** IUPAC name (2-[4-(2-methylpropyl)phenyl]propanoic acid), a **generic** name (ibuprofen) and a **trade** name (Motrin, Advil).' },
      ],
    },
    {
      id: 'naming',
      title: 'Naming alkanes step by step',
      minutes: 12,
      blocks: [
        {
          t: 'steps', title: 'HOW TO name an alkane', items: [
            '**Find the longest continuous carbon chain** (the parent). It may bend! Name it (hexane, heptane…).',
            '**Number the chain** from the end **closer to the first branch**.',
            '**Name and number each substituent.** Every substituent gets its own number.',
            'Identical substituents: use **di-, tri-, tetra-** and list every number (2,3-dimethyl).',
            '**Alphabetize** the substituents, ignoring di-/tri-/tetra- (and sec-/tert-, but not iso-).',
            '**Punctuation:** commas between numbers, hyphens between numbers and words, no space before the parent.',
          ],
        },
        {
          t: 'example', title: 'Example: one branch', prompt: 'Name this alkane.',
          mol: { smiles: 'CC(C)CCCC', numbers: 'auto' },
          steps: ['Longest chain: **6 C** → hexane.', 'Number from the end nearer the branch: the methyl is on **C2** (from the other end it would be C5).', 'Substituent: **methyl** at 2.'],
          answer: '**2-methylhexane**',
        },
        {
          t: 'example', title: 'Example: two identical branches', prompt: 'Name this alkane.',
          mol: { smiles: 'CC(C)C(C)CCC', numbers: 'auto' },
          steps: ['Longest chain: 6 C → hexane.', 'Number from the left: methyls on C2 and C3 (from the right: C4 and C5 — higher).', 'Two methyls → **di**methyl, with both numbers.'],
          answer: '**2,3-dimethylhexane**',
        },
        {
          t: 'example', title: 'Example: the longest chain bends', prompt: 'Name this alkane.',
          mol: { smiles: 'CCC(C)CCC', numbers: 'auto' },
          steps: ['The horizontal chain looks like 5 carbons, but going **down the branch** gives a longer chain of **6**.', 'Every carbon belongs to either the chain or a substituent — never both.', 'Numbering from either end puts the methyl on C3.'],
          answer: '**3-methylhexane** (NOT 2-ethylpentane)',
        },
        {
          t: 'example', title: 'Example: alphabetical order', prompt: 'Name this alkane.',
          mol: { smiles: 'CC(C)CCC(CC)C(C)CC', numbers: 'auto' },
          steps: ['Longest chain: **8 C** → octane.', 'Numbering from the left gives branches at 2, 5, 6; from the right 3, 4, 7. First point of difference: 2 < 3 → number from the left.', 'Branches: methyl (C2), ethyl (C5), methyl (C6) → **5-ethyl** and **2,6-dimethyl**.', 'Alphabetize: **e**thyl before **m**ethyl (ignore "di").'],
          answer: '**5-ethyl-2,6-dimethyloctane**',
        },
        { t: 'callout', kind: 'warn', title: 'The 5 most common naming mistakes', text: '1. Using a chain that isn\'t the **longest** (check around corners!).\n2. Numbering from the wrong end — find the **first point of difference**.\n3. Writing 2-methyl-3-methyl instead of **2,3-dimethyl**.\n4. Putting substituents in number order instead of **alphabetical** order.\n5. An ethyl on C2 or a methyl on C1 — that means your chain isn\'t the longest.' },
        { t: 'callout', kind: 'tip', title: 'Tie-breaker', text: 'If both numbering directions give the same numbers, give the **lower number to the substituent that comes first alphabetically**: 2-**b**romo-5-**m**ethylhexane.' },
        {
          t: 'check', q: {
            id: 'l03-c-name1', skill: 'l03.naming', type: 'name', prompt: 'Name this alkane.',
            figure: { smiles: 'CC(C)CC(C)C(CC)CCC' }, name: { smiles: 'CC(C)CC(C)C(CC)CCC' },
            explain: 'Longest chain 8 C (octane); branches at 2, 4 (methyls) and 5 (ethyl) → **5-ethyl-2,4-dimethyloctane**.',
          },
        },
        { t: 'link', text: 'Try the Name Lab — type any name and see it drawn →', href: '#/lab' },
      ],
    },
    {
      id: 'drawing',
      title: 'Drawing a structure from its name',
      minutes: 6,
      blocks: [
        {
          t: 'steps', title: 'Work backwards', items: ['Find the **parent** at the end of the name and draw that many carbons as a zig-zag.', 'Number the chain from one end.', 'Attach each substituent at its number.', 'Check: every carbon has 4 bonds; re-name your drawing to confirm.'],
        },
        {
          t: 'example', title: 'Practice from class', prompt: 'Draw 5-ethyl-2,6-dimethyloctane.',
          steps: ['Parent: **octane** → 8-carbon zig-zag, numbered 1–8.', '**2,6-dimethyl** → a $CH_3$ on C2 and on C6.', '**5-ethyl** → a $CH_2CH_3$ on C5.'],
          mol: { smiles: 'CC(C)CCC(CC)C(C)CC', numbers: 'auto' },
          answer: 'Octane chain with methyls on C2 and C6 and an ethyl on C5.',
        },
        { t: 'mols', items: [{ smiles: 'CC(C)CCC', caption: '2-methylpentane', numbers: 'auto' }] },
      ],
    },
    {
      id: 'cyclo',
      title: 'Naming cycloalkanes',
      minutes: 6,
      blocks: [
        { t: 'p', text: 'For a ring: **prefix** (substituents) + **cyclo** + **parent** (number of ring carbons) + **-ane**.' },
        { t: 'list', items: ['**One substituent:** no number needed → methylcyclohexane.', '**Two or more substituents:** number the ring to give the lowest numbers; if there\'s a tie, the substituent that comes **first alphabetically gets C1**.'] },
        {
          t: 'mols', items: [
            { smiles: 'CC1CCCCC1', caption: 'methylcyclohexane', name: 'methylcyclohexane' },
            { smiles: 'CCC1CCCC(C)C1', caption: '1-ethyl-3-methylcyclohexane', numbers: 'auto', name: '1-ethyl-3-methylcyclohexane' },
            { smiles: 'CC1(C)CCCC1', caption: '1,1-dimethylcyclopentane', numbers: 'auto', name: '1,1-dimethylcyclopentane' },
          ],
        },
        {
          t: 'check', q: {
            id: 'l03-c-cyclo', skill: 'l03.naming', type: 'name', prompt: 'Name this cycloalkane.',
            figure: { smiles: 'CCC1CCC(C)CC1' }, name: { smiles: 'CCC1CCC(C)CC1' },
            explain: 'Ring of 6 → cyclohexane. Substituents 1,4 either way; alphabetical tie-break gives **ethyl** C1 → **1-ethyl-4-methylcyclohexane**.',
          },
        },
      ],
    },
  ],
  questions: [
    { id: 'l03-q01', skill: 'l03.formulas', type: 'mc', prompt: 'Which formula is an acyclic **alkane**?', choices: ['$C_7H_{16}$', '$C_7H_{14}$', '$C_7H_{12}$', '$C_7H_{18}$'], answer: 0, explain: '$C_nH_{2n+2}$: 2(7)+2 = 16 → **$C_7H_{16}$** (heptane).' },
    { id: 'l03-q02', skill: 'l03.formulas', type: 'tf', prompt: 'True or false: cyclohexane and 1-hexene have the same molecular formula.', answer: true, explain: '**True** — both are $C_6H_{12}$. They are constitutional isomers. A ring and a C=C each "cost" 2 H.' },
    { id: 'l03-q03', skill: 'l03.formulas', type: 'mc', prompt: 'Why are acyclic alkanes called **saturated**?', choices: ['They have the maximum number of H atoms per C', 'They dissolve completely in water', 'They contain double bonds', 'They are solids'], answer: 0, explain: 'Saturated = holds as many H as possible (only single bonds, no rings).' },
    { id: 'l03-q04', skill: 'l03.isomers', type: 'mc', prompt: 'Butane and isobutane (2-methylpropane) are…', choices: ['constitutional isomers', 'the same compound', 'not isomers', 'stereoisomers'], answer: 0, explain: 'Both $C_4H_{10}$ with atoms connected differently → **constitutional isomers**.' },
    { id: 'l03-q05', skill: 'l03.isomers', type: 'num', prompt: 'How many constitutional isomers have the formula $C_5H_{12}$?', answer: 3, tol: 0, explain: '**3**: pentane, 2-methylbutane, and 2,2-dimethylpropane.' },
    { id: 'l03-q06', skill: 'l03.isomers', type: 'mc', prompt: 'What is the molecular formula shared by ethanol and dimethyl ether?', choices: ['$C_2H_6O$', '$C_2H_5O$', '$C_2H_4O$', '$CH_4O$'], answer: 0, explain: 'Both are **$C_2H_6O$** — isomers from different families.' },
    { id: 'l03-q07', skill: 'l03.carbon-class', type: 'mc', prompt: 'A carbon bonded to **three** other carbons is…', choices: ['primary (1°)', 'secondary (2°)', 'tertiary (3°)', 'quaternary (4°)'], answer: 2, shuffle: false, explain: 'Count carbon neighbours: 3 → **tertiary**.' },
    { id: 'l03-q08', skill: 'l03.carbon-class', type: 'num', prompt: 'How many **primary (1°)** carbons are in 2,2,4-trimethylpentane?', figure: { smiles: 'CC(C)(C)CC(C)C' }, answer: 5, tol: 0, explain: 'Every $CH_3$ is 1°: the three on C2 side (C1 and two methyls) + the two on C4 (C5 and the methyl) = **5**.' },
    { id: 'l03-q09', skill: 'l03.naming', type: 'mc', prompt: 'Which is the correct way to write this name?', choices: ['2,3-dimethylpentane', '2-3-dimethylpentane', '2,3-dimethyl pentane', '2-methyl-3-methylpentane'], answer: 0, explain: 'Commas between numbers, hyphen between number and word, no space before the parent, and combine identical groups with **di-**.' },
    { id: 'l03-q10', skill: 'l03.naming', type: 'mc', prompt: 'Why is "2-ethylpentane" never a correct name?', choices: ['An ethyl on C2 extends the chain — the real parent is hexane', 'Ethyl groups must be on C1', 'Pentane can\'t have branches', 'It should be 2-ethylpentyl'], answer: 0, explain: 'An ethyl on C2 makes a 6-carbon chain. The correct name is **3-methylhexane**.' },
    { id: 'l03-q11', skill: 'l03.naming', type: 'mc', prompt: 'In alphabetizing, which prefix is **ignored**?', choices: ['di-', 'iso-', 'cyclo-', 'none of them'], answer: 0, explain: 'Multiplying prefixes (**di-, tri-, tetra-**) are ignored; so are sec- and tert-. "Iso-" and "cyclo-" count.' },
    { id: 'l03-q12', skill: 'l03.naming', type: 'name', prompt: 'Name this alkane.', figure: { smiles: 'CC(C)CC(C)(C)CC' }, name: { smiles: 'CC(C)CC(C)(C)CC' }, explain: 'Longest chain = 6 → hexane. Number from the left: methyls at 2, 4, 4 (right would give 3, 3, 5). → **2,4,4-trimethylhexane**.' },
    { id: 'l03-q13', skill: 'l03.naming', type: 'name', prompt: 'Name this alkane.', figure: { smiles: 'CCC(CC)C(C)C' }, name: { smiles: 'CCC(CC)C(C)C' }, explain: 'Longest chain = 5 → pentane (either 5-carbon path). Branches: methyl at 2, ethyl at 3 → **3-ethyl-2-methylpentane**.' },
    { id: 'l03-q14', skill: 'l03.drawing', type: 'struct', prompt: 'Which structure is **2-methylpentane**?', choices: [{ smiles: 'CC(C)CCC' }, { smiles: 'CCC(C)CC' }, { smiles: 'CC(C)CCCC' }, { smiles: 'CC(C)(C)CC' }], answer: 0, explain: 'Pentane (5 C) with a methyl on C2. The others are 3-methylpentane, 2-methylhexane and 2,2-dimethylbutane.' },
    { id: 'l03-q15', skill: 'l03.drawing', type: 'num', prompt: 'How many carbons does **5-ethyl-2,6-dimethyloctane** have in total?', answer: 12, tol: 0, explain: 'Octane (8) + ethyl (2) + two methyls (2) = **12** carbons.' },
    { id: 'l03-q16', skill: 'l03.naming', type: 'name', prompt: 'Name this cycloalkane.', figure: { smiles: 'CC1CCC(C(C)C)CC1' }, name: { smiles: 'CC1CCC(C(C)C)CC1' }, explain: 'Cyclohexane with substituents at 1 and 4. Tie → alphabetical: **i**sopropyl before **m**ethyl → **1-isopropyl-4-methylcyclohexane**.' },
  ],
  cards: [
    { id: 'l03-k01', front: 'General formula of acyclic alkanes', back: '$C_nH_{2n+2}$ (saturated)' },
    { id: 'l03-k02', front: 'General formula of cycloalkanes', back: '$C_nH_{2n}$' },
    { id: 'l03-k03', front: 'Prefixes for 1–5 carbons', back: '1 meth · 2 eth · 3 prop · 4 but · 5 pent' },
    { id: 'l03-k04', front: 'Prefixes for 6–10 carbons', back: '6 hex · 7 hept · 8 oct · 9 non · 10 dec' },
    { id: 'l03-k05', front: 'Isomers', back: 'Different compounds with the **same molecular formula**.' },
    { id: 'l03-k06', front: 'Constitutional isomers', back: 'Isomers whose atoms are **connected differently** (e.g. butane and isobutane).' },
    { id: 'l03-k07', front: '1°, 2°, 3°, 4° carbon', back: 'Bonded to **1, 2, 3, or 4 other carbons**.' },
    { id: 'l03-k08', front: 'Three parts of an IUPAC name', back: '**Prefix** (substituents) + **parent** (longest chain) + **suffix** (functional group).' },
    { id: 'l03-k09', front: 'Alkyl group names', back: 'Change -ane to **-yl**: methyl, ethyl, propyl, butyl… (isopropyl = $(CH_3)_2CH$–)' },
    { id: 'l03-k10', front: 'Naming step 1', back: 'Find the **longest continuous carbon chain** (it may bend).' },
    { id: 'l03-k11', front: 'Numbering rule', back: 'Number from the end that gives the **first substituent the lower number** (first point of difference).' },
    { id: 'l03-k12', front: 'Numbering tie-breaker', back: 'The substituent that comes **first alphabetically** gets the lower number.' },
    { id: 'l03-k13', front: 'Alphabetizing substituents', back: 'Alphabetical order, **ignoring di-, tri-, tetra-, sec-, tert-** (iso- counts).' },
    { id: 'l03-k14', front: 'Name this', mol: 'CCC(C)CCC', back: '**3-methylhexane** (the longest chain turns the corner!).' },
    { id: 'l03-k15', front: 'Name this', mol: 'CC(C)C(C)CCC', back: '**2,3-dimethylhexane**' },
    { id: 'l03-k16', front: 'Cycloalkane with one substituent', back: 'No number needed: e.g. **methylcyclohexane**.' },
    { id: 'l03-k17', front: 'Three names of a drug', back: '**Systematic** (IUPAC), **generic** (ibuprofen), **trade** (Advil/Motrin).' },
  ],
  keyTerms: [
    { term: 'alkane', def: 'A hydrocarbon with only C–C and C–H single bonds.' },
    { term: 'saturated', def: 'Having the maximum number of H atoms per carbon (no multiple bonds or rings).' },
    { term: 'constitutional isomers', def: 'Isomers that differ in how their atoms are connected.' },
    { term: 'IUPAC', def: 'International Union of Pure and Applied Chemistry — sets the naming rules.' },
    { term: 'substituent', def: 'A group (branch) attached to the main chain.' },
    { term: 'parent chain', def: 'The longest continuous carbon chain; it gives the root of the name.' },
    { term: 'cycloalkane', def: 'An alkane whose carbons form a ring (CₙH₂ₙ).' },
  ],
};
