// Lecture 4 — Unsaturated Hydrocarbons (Smith Ch. 13.1–13.7)
export default {
  id: 'l04',
  number: 4,
  title: 'Alkenes & Alkynes',
  subtitle: 'Naming, cis/trans isomers, fats & addition reactions',
  chapter: 'Ch. 13.1–13.7',
  tested: true,
  summary: 'Double and triple bonds: how to name them, why C=C gives cis/trans isomers, what that means for fats and oils, and the four addition reactions (with Markovnikov\'s rule).',
  skills: [
    { id: 'l04.formulas', title: 'Alkene & alkyne formulas', desc: 'CₙH₂ₙ and CₙH₂ₙ₋₂; unsaturation.' },
    { id: 'l04.naming', title: 'Naming alkenes & alkynes', desc: '-ene/-yne, lowest number to the multiple bond, dienes, cycloalkenes.' },
    { id: 'l04.cis-trans', title: 'Cis/trans isomers', desc: 'Same side vs opposite sides; when cis/trans is possible.' },
    { id: 'l04.fats', title: 'Fats, oils & margarine', desc: 'Saturated vs unsaturated fatty acids; partial hydrogenation.' },
    { id: 'l04.addition', title: 'Addition reactions', desc: 'Hydrogenation and halogenation of alkenes.' },
    { id: 'l04.markovnikov', title: 'Markovnikov\'s rule', desc: 'Adding HX and H₂O to unsymmetrical alkenes.' },
  ],
  sections: [
    {
      id: 'intro',
      title: 'Alkenes and alkynes',
      minutes: 4,
      blocks: [
        {
          t: 'compare', items: [
            { title: 'Alkenes: C=C, $C_nH_{2n}$', text: 'Contain a carbon–carbon **double bond**. Each C of the C=C is trigonal planar (120°).' },
            { title: 'Alkynes: C≡C, $C_nH_{2n-2}$', text: 'Contain a carbon–carbon **triple bond**. Each C of the C≡C is linear (180°).' },
          ],
        },
        { t: 'p', text: 'They are called **unsaturated** hydrocarbons because they have **fewer than the maximum number of H atoms** per C. Their bonds are nonpolar, so — like alkanes — they have **low melting and boiling points** and are **insoluble in water**.' },
        { t: 'mols', items: [{ smiles: 'C=CCC', caption: '1-butene, $C_4H_8$' }, { smiles: 'CC#CC', caption: '2-butyne, $C_4H_6$' }] },
        { t: 'callout', kind: 'tip', title: 'Condensed structures', text: 'The multiple bond is always drawn in a condensed structure: $CH_2=CHCH_2CH_3$, $CH_3C≡CCH_3$.' },
      ],
    },
    {
      id: 'naming',
      title: 'Naming alkenes and alkynes',
      minutes: 10,
      blocks: [
        {
          t: 'steps', title: 'HOW TO name an alkene or alkyne', items: [
            'Find the **longest chain that contains both carbons of the C=C (or C≡C)**. Change -ane to **-ene** (alkene) or **-yne** (alkyne).',
            '**Number the chain from the end that gives the multiple bond the lower number.** Use the **first** carbon of the multiple bond in the name.',
            'Number and name the substituents as usual, alphabetize, and write the name.',
          ],
        },
        { t: 'mols', items: [{ smiles: 'C=CCC', caption: '1-butene', numbers: 'auto', name: '1-butene' }, { smiles: 'CC#CCCC', caption: '2-hexyne', numbers: 'auto', name: '2-hexyne' }] },
        {
          t: 'example', title: 'The multiple bond wins the numbering', prompt: 'Name this alkene.',
          mol: { smiles: 'CC(C)CC=CC', numbers: 'auto' },
          steps: ['Longest chain containing the C=C: 6 C → hex**ene**.', 'Number from the right so the C=C starts at **C2** (from the left it would start at C4).', 'The methyl is then on **C5**.'],
          answer: '**5-methyl-2-hexene** — the double bond gets priority over the branch.',
        },
        {
          t: 'example', title: 'Practice from class', prompt: 'Draw 4,4-dimethyl-2-pentyne.',
          steps: ['Parent: 2-pent**yne** → 5 carbons with a C≡C between C2 and C3.', 'Two methyls on **C4**.', 'The C≡C part is drawn straight (180°).'],
          mol: { smiles: 'CC#CC(C)(C)C', numbers: 'auto' },
          answer: '$CH_3C≡CC(CH_3)_2CH_3$',
        },
        { t: 'h', text: 'Dienes' },
        { t: 'p', text: 'Two C=C bonds → **-adiene**, and each double bond gets its own number.' },
        { t: 'mols', items: [{ smiles: 'C=CC=C', caption: '1,3-butadiene', numbers: 'auto', name: '1,3-butadiene' }, { smiles: 'C=CCC=C(C)C', caption: '5-methyl-1,4-hexadiene', numbers: 'auto', name: '5-methyl-1,4-hexadiene' }] },
        { t: 'h', text: 'Cycloalkenes' },
        { t: 'p', text: 'In a ring, the C=C is always between **C1 and C2** (the "1" is left out). Then number to give the first substituent the lower number.' },
        { t: 'mols', items: [{ smiles: 'CC1=CCCC1', caption: '1-methylcyclopentene', numbers: 'auto', name: '1-methylcyclopentene' }, { smiles: 'CC1=CCCCC1C', caption: '1,6-dimethylcyclohexene', numbers: 'auto', name: '1,6-dimethylcyclohexene' }] },
        { t: 'callout', kind: 'warn', title: 'Common mistakes', text: '- Choosing a longer chain that **doesn\'t contain the C=C** — the chain must include both C=C carbons.\n- Numbering to favor a branch instead of the **multiple bond**.\n- Writing the locant of the second carbon of the double bond (it\'s always the **first/lower** one).' },
        {
          t: 'check', q: {
            id: 'l04-c-name', skill: 'l04.naming', type: 'name', prompt: 'Name this compound.',
            figure: { smiles: 'CC=C(CCC)CCC' }, name: { smiles: 'CC=C(CCC)CCC' },
            explain: 'Longest chain with the C=C: 6 C (either propyl arm works) → hexene; C=C at 2; propyl on C3 → **3-propyl-2-hexene**.',
          },
        },
      ],
    },
    {
      id: 'cis-trans',
      title: 'Cis–trans isomers',
      minutes: 8,
      blocks: [
        { t: 'p', text: 'Atoms can\'t rotate around a C=C (rotation would break the second bond). So in 2-butene, the two $CH_3$ groups can be locked on the **same side** or on **opposite sides** — two different compounds!' },
        { t: 'mols', items: [{ smiles: 'C/C=C\\C', caption: 'cis-2-butene: same side' }, { smiles: 'C/C=C/C', caption: 'trans-2-butene: opposite sides' }] },
        { t: 'callout', kind: 'key', title: 'When is cis/trans possible?', text: 'Only when **each carbon of the C=C has two DIFFERENT groups**. If either carbon has two identical groups (two H\'s, two CH₃\'s…), there is no cis or trans.' },
        { t: 'mols', items: [{ smiles: 'C=CCC', caption: '1-butene: C1 has two H → no cis/trans', mode: 'condensed' }, { smiles: 'CC(C)=CC', caption: '2-methyl-2-butene: two CH₃ on one C → no cis/trans', mode: 'condensed' }] },
        {
          t: 'compare', items: [
            { title: 'Stereoisomers', text: 'Same connections, **different 3-D arrangement** (cis vs trans).' },
            { title: 'Constitutional isomers', text: 'Atoms **bonded in a different order** (1-butene vs 2-butene).' },
          ],
        },
        { t: 'callout', kind: 'memory', title: 'Memory trick', text: '**Cis** = **s**ame **s**ide. **Trans** = across (like trans-Atlantic).' },
      ],
    },
    {
      id: 'fats',
      title: 'Fatty acids, fats & oils',
      minutes: 7,
      blocks: [
        { t: 'p', text: '**Fatty acids** are carboxylic acids (RCOOH) with long carbon chains of **12–20 carbons**. Animal fats and vegetable oils are made from them.' },
        {
          t: 'compare', items: [
            { title: 'Saturated fatty acids', text: '**No** C=C in the chain. Chains pack tightly → **higher melting point** → fats are **solid** at room temperature (butter).' },
            { title: 'Unsaturated fatty acids', text: '**One or more** C=C, usually **cis** in nature. Each cis C=C puts a **kink** in the chain → can\'t pack → **lower melting point** → oils are **liquid**.' },
          ],
        },
        { t: 'mols', items: [{ smiles: 'CCCCCCCCCCCCCCCCCC(=O)O', caption: 'stearic acid (saturated)' }, { smiles: 'CCCCCCCC/C=C\\CCCCCCCC(=O)O', caption: 'oleic acid (one cis C=C — note the kink)' }] },
        { t: 'callout', kind: 'key', title: 'Rule', text: 'As the number of double bonds **increases**, the melting point **decreases**.' },
        { t: 'h', text: 'Margarine or butter?' },
        { t: 'p', text: 'Butter is made mostly of saturated fatty acids (a diet high in them is considered unhealthy). To make a solid butter substitute from liquid vegetable oil, manufacturers **partially hydrogenate** it: some C=C bonds get H₂ added, raising the melting point.' },
        { t: 'callout', kind: 'life', title: 'Trans fats', text: 'Partial hydrogenation leaves a few C=C bonds, and some are flipped from cis to **trans** — "trans fats," which do not occur naturally and are linked to heart disease.' },
        { t: 'h', text: 'Interesting alkenes' },
        { t: 'list', items: ['**Lycopene** (red color of tomatoes and watermelon) has 13 C=C bonds and is an **antioxidant** (prevents unwanted oxidation). Diets rich in antioxidants lower the risk of heart disease and cancer.', '**Tamoxifen** treats breast cancers that need estrogen to grow.', '**Oral contraceptives** (ethynylestradiol, norethindrone) resemble estradiol and progesterone but contain a **C≡C triple bond**.'] },
      ],
    },
    {
      id: 'addition',
      title: 'Addition reactions of alkenes',
      minutes: 10,
      blocks: [
        { t: 'p', text: 'Alkenes undergo **addition**: one bond of the C=C breaks and two new single bonds form — a new group X adds to one carbon and Y to the other.' },
        {
          t: 'table', head: ['Reaction', 'Reagent', 'Adds', 'Product'],
          rows: [
            ['**Hydrogenation**', 'H₂ + Pd catalyst', 'H and H', '**alkane**'],
            ['**Halogenation**', 'X₂ (Cl₂ or Br₂), no catalyst', 'X and X', '**dihalide**'],
            ['**Hydrohalogenation**', 'HX (HCl or HBr)', 'H and X', '**alkyl halide**'],
            ['**Hydration**', 'H₂O + H₂SO₄ (strong acid)', 'H and OH', '**alcohol**'],
          ],
        },
        { t: 'rxn', from: 'CC=CC', reagent: 'H₂, Pd', to: 'CCCC', caption: 'Hydrogenation: 2-butene → butane' },
        { t: 'rxn', from: 'C1=CCCCC1', reagent: 'Br₂', to: 'BrC1CCCCC1Br', caption: 'Halogenation: cyclohexene → 1,2-dibromocyclohexane' },
        { t: 'rxn', from: 'C=C', reagent: 'HCl', to: 'CCCl', caption: 'Hydrohalogenation: ethylene → chloroethane' },
        { t: 'rxn', from: 'C=C', reagent: 'H₂O, H₂SO₄', to: 'CCO', caption: 'Hydration: ethylene → ethanol' },
        { t: 'h', text: 'Markovnikov\'s rule' },
        { t: 'p', text: 'When H–X or H–OH adds to an **unsymmetrical** alkene, two products are possible (constitutional isomers). Only one forms as the major product:' },
        { t: 'callout', kind: 'key', title: 'Markovnikov\'s rule', text: 'The **H** of H–X adds to the **less substituted** carbon of the C=C — the one that **already has more H\'s**. X (or OH) ends up on the **more substituted** carbon.' },
        { t: 'callout', kind: 'memory', title: 'Memory trick', text: '"**The rich get richer**" — the carbon that is already H-rich gets the new H.' },
        { t: 'rxn', from: 'C=CC', reagent: 'HCl', to: 'CC(Cl)C', caption: 'Propene + HCl → 2-chloropropane (major), not 1-chloropropane' },
        { t: 'rxn', from: 'C=CC', reagent: 'H₂O, H₂SO₄', to: 'CC(O)C', caption: 'Propene + H₂O → 2-propanol (major)' },
        {
          t: 'check', q: {
            id: 'l04-c-markov', skill: 'l04.markovnikov', type: 'struct', prompt: 'Circle the **main product**: 1-methylcyclohexene + HCl →',
            figure: { rxn: { from: 'CC1=CCCCC1', reagent: 'HCl' } },
            choices: [{ smiles: 'CC1(Cl)CCCCC1' }, { smiles: 'CC1CCCCC1Cl' }], answer: 0, shuffle: false,
            explain: 'The ring CH of the C=C has 1 H; the other C=C carbon (holding the CH₃) has 0 H. H goes to the CH ("rich get richer"), so **Cl goes on the carbon with the methyl**.',
          },
        },
        { t: 'callout', kind: 'warn', title: 'Where students lose points', text: '- Mixing up **halogenation** (X₂ → two X\'s) with **hydrohalogenation** (HX → one H, one X).\n- Forgetting **Markovnikov** on unsymmetrical alkenes.\n- Forgetting that hydration needs **H₂SO₄** and hydrogenation needs a **Pd** catalyst.' },
      ],
    },
  ],
  questions: [
    { id: 'l04-q01', skill: 'l04.formulas', type: 'mc', prompt: 'Why are alkenes called **unsaturated**?', choices: ['They have fewer than the maximum number of H atoms per C', 'They dissolve in water', 'They have no hydrogens', 'They are ionic'], answer: 0, explain: 'A C=C means fewer H\'s than the alkane with the same carbons.' },
    { id: 'l04-q02', skill: 'l04.formulas', type: 'tf', prompt: 'True or false: alkenes are soluble in water because the C=C bond is polar.', answer: false, explain: '**False.** C=C is nonpolar. Alkenes are insoluble in water with low boiling points, like alkanes.' },
    { id: 'l04-q03', skill: 'l04.naming', type: 'mc', prompt: 'What is wrong with the name **3-butene**?', choices: ['Numbering should start from the other end: it is 1-butene', 'Butene can\'t have a double bond at C3', 'It needs a methyl group', 'Nothing is wrong'], answer: 0, explain: 'Number so the C=C gets the **lowest** number → **1-butene**.' },
    { id: 'l04-q04', skill: 'l04.naming', type: 'name', prompt: 'Name this alkyne.', figure: { smiles: 'CC#CC(C)(C)C' }, name: { smiles: 'CC#CC(C)(C)C' }, explain: '5-carbon chain with the C≡C at C2 and two methyls on C4 → **4,4-dimethyl-2-pentyne**.' },
    { id: 'l04-q05', skill: 'l04.naming', type: 'name', prompt: 'Name this diene.', figure: { smiles: 'C=CC=C' }, name: { smiles: 'C=CC=C' }, explain: 'Four carbons, double bonds starting at C1 and C3 → **1,3-butadiene**.' },
    { id: 'l04-q06', skill: 'l04.naming', type: 'name', prompt: 'Name this cycloalkene.', figure: { smiles: 'CC1=CCCC1' }, name: { smiles: 'CC1=CCCC1' }, explain: 'Ring C=C is C1–C2; give the methyl the lowest number → it sits on C1 → **1-methylcyclopentene**.' },
    { id: 'l04-q07', skill: 'l04.cis-trans', type: 'mc', prompt: 'Why do cis and trans isomers exist for 2-butene but not for 2-butane?', choices: ['There is no rotation around a C=C bond', 'Butane has too few carbons', 'Double bonds are longer', 'Single bonds are polar'], answer: 0, explain: '**Restricted rotation** around the C=C locks groups on one side or the other. C–C single bonds rotate freely.' },
    { id: 'l04-q08', skill: 'l04.cis-trans', type: 'mc', prompt: 'Cis-2-butene and trans-2-butene are…', choices: ['stereoisomers', 'constitutional isomers', 'the same compound', 'not isomers'], answer: 0, explain: 'Same connections, different 3-D arrangement → **stereoisomers**.' },
    { id: 'l04-q09', skill: 'l04.fats', type: 'mc', prompt: 'Which fatty acid has the **lowest** melting point?', choices: ['one with three cis C=C bonds', 'one with one cis C=C bond', 'a saturated fatty acid', 'they are all the same'], answer: 0, explain: 'More C=C (kinks) → worse packing → **lower** melting point.' },
    { id: 'l04-q10', skill: 'l04.fats', type: 'mc', prompt: 'Vegetable oil is turned into solid margarine by…', choices: ['partial hydrogenation', 'hydration', 'halogenation', 'adding more C=C bonds'], answer: 0, explain: '**Partial hydrogenation** adds H₂ to some C=C bonds, raising the melting point.' },
    { id: 'l04-q11', skill: 'l04.fats', type: 'tf', prompt: 'True or false: double bonds in naturally occurring fatty acids are usually **cis**.', answer: true, explain: '**True.** Trans fats mostly come from partial hydrogenation.' },
    { id: 'l04-q12', skill: 'l04.fats', type: 'mc', prompt: 'Lycopene, the red pigment in tomatoes, is valued because it is…', choices: ['an antioxidant', 'a trans fat', 'an alkyne', 'a saturated fat'], answer: 0, explain: 'Lycopene (13 C=C) is an **antioxidant** — it prevents unwanted oxidation.' },
    { id: 'l04-q13', skill: 'l04.addition', type: 'mc', prompt: 'What catalyst is used for hydrogenation?', choices: ['Pd (palladium)', 'H₂SO₄', 'NaOH', 'none is needed'], answer: 0, explain: 'H₂ adds to C=C with a metal catalyst, usually **Pd**.' },
    { id: 'l04-q14', skill: 'l04.addition', type: 'match', prompt: 'Match each reaction to its product type.', left: ['hydrogenation', 'halogenation', 'hydrohalogenation', 'hydration'], right: ['alkane', 'dihalide', 'alkyl halide', 'alcohol'], answer: [0, 1, 2, 3], explain: 'H₂ → alkane; X₂ → dihalide; HX → alkyl halide; H₂O → alcohol.' },
    { id: 'l04-q15', skill: 'l04.markovnikov', type: 'mc', prompt: 'In the reaction of propene ($CH_2=CHCH_3$) with HBr, the H adds to…', choices: ['C1 (the $CH_2$ end, which has more H\'s)', 'C2 (the CH)', 'C3 (the $CH_3$)', 'both equally'], answer: 0, explain: 'Markovnikov: H adds to the C=C carbon with **more H\'s** (C1), Br goes to C2 → **2-bromopropane**.' },
    { id: 'l04-q16', skill: 'l04.markovnikov', type: 'struct', prompt: 'What is the major product of 2-methylpropene + H₂O (H₂SO₄)?', figure: { rxn: { from: 'C=C(C)C', reagent: 'H₂O, H₂SO₄' } }, choices: [{ smiles: 'CC(C)(C)O' }, { smiles: 'CC(C)CO' }, { smiles: 'CC(C)C' }, { smiles: 'OCC(C)(C)O' }], answer: 0, explain: 'H goes to the $CH_2$ end; OH goes to the carbon with two methyls → **2-methyl-2-propanol** (a 3° alcohol).' },
  ],
  cards: [
    { id: 'l04-k01', front: 'Alkene general formula', back: '$C_nH_{2n}$ (one C=C)' },
    { id: 'l04-k02', front: 'Alkyne general formula', back: '$C_nH_{2n-2}$ (one C≡C)' },
    { id: 'l04-k03', front: 'Unsaturated hydrocarbon', back: 'Has fewer than the maximum number of H per C (contains C=C or C≡C).' },
    { id: 'l04-k04', front: 'Naming rule #1 for alkenes', back: 'Longest chain that **contains both C=C carbons**; -ane → **-ene** (or **-yne**).' },
    { id: 'l04-k05', front: 'Naming rule #2 for alkenes', back: 'Number so the **multiple bond** gets the lower number; name uses its **first** carbon.' },
    { id: 'l04-k06', front: 'Diene naming', back: '-ane → **-adiene**; each C=C gets a number (1,3-butadiene).' },
    { id: 'l04-k07', front: 'Cycloalkene numbering', back: 'The C=C is **C1–C2**; the "1" is omitted.' },
    { id: 'l04-k08', front: 'Cis vs trans', back: '**Cis**: groups on the same side. **Trans**: opposite sides.' },
    { id: 'l04-k09', front: 'Requirement for cis/trans isomers', back: '**Each** C of the C=C must have **two different groups**.' },
    { id: 'l04-k10', front: 'Stereoisomers', back: 'Same connections, different **3-D arrangement**.' },
    { id: 'l04-k11', front: 'Saturated vs unsaturated fats', back: 'Saturated: no C=C, solid (fats). Unsaturated: cis C=C kinks, liquid (oils).' },
    { id: 'l04-k12', front: 'More C=C in a fatty acid →', back: '**Lower** melting point.' },
    { id: 'l04-k13', front: 'Hydrogenation', back: 'Alkene + **H₂, Pd** → **alkane**' },
    { id: 'l04-k14', front: 'Halogenation', back: 'Alkene + **X₂** (Cl₂/Br₂, no catalyst) → **dihalide** (X on each carbon)' },
    { id: 'l04-k15', front: 'Hydrohalogenation', back: 'Alkene + **HX** → **alkyl halide** (Markovnikov)' },
    { id: 'l04-k16', front: 'Hydration', back: 'Alkene + **H₂O, H₂SO₄** → **alcohol** (Markovnikov)' },
    { id: 'l04-k17', front: 'Markovnikov\'s rule', back: 'The **H** adds to the C=C carbon that already has **more H\'s**; X/OH goes to the more substituted carbon. "The rich get richer."' },
    { id: 'l04-k18', front: 'Trans fats come from…', back: '**Partial hydrogenation** of vegetable oils (some cis C=C become trans).' },
  ],
  keyTerms: [
    { term: 'alkene', def: 'A hydrocarbon containing a C=C double bond.' },
    { term: 'alkyne', def: 'A hydrocarbon containing a C≡C triple bond.' },
    { term: 'unsaturated', def: 'Containing fewer than the maximum number of H atoms per carbon.' },
    { term: 'stereoisomers', def: 'Isomers that differ only in the 3-D arrangement of atoms.' },
    { term: 'cis isomer', def: 'Two groups on the same side of a C=C.' },
    { term: 'trans isomer', def: 'Two groups on opposite sides of a C=C.' },
    { term: 'fatty acid', def: 'A carboxylic acid with a long (12–20 C) carbon chain.' },
    { term: 'addition reaction', def: 'A reaction where groups add across a multiple bond.' },
    { term: 'Markovnikov\'s rule', def: 'In HX/H₂O addition, H bonds to the less substituted carbon of the C=C.' },
    { term: 'antioxidant', def: 'A compound that prevents unwanted oxidation.' },
  ],
};
