// Lecture 5 — Alcohols (Smith Ch. 14.1–14.7)
export default {
  id: 'l05',
  number: 5,
  title: 'Alcohols',
  subtitle: 'Classification, properties, naming, dehydration & oxidation',
  chapter: 'Ch. 14.1–14.7',
  tested: false,
  summary: 'Alcohols (R–OH): how to classify and name them, why they boil higher than hydrocarbons, and their two big reactions — dehydration (Zaitsev) and oxidation (1°, 2°, 3°).',
  skills: [
    { id: 'l05.classify', title: 'Classifying alcohols', desc: '1°, 2°, 3° alcohols.' },
    { id: 'l05.properties', title: 'Properties of alcohols', desc: 'H-bonding, boiling points and water solubility.' },
    { id: 'l05.naming', title: 'Naming alcohols', desc: '-ol, lowest number to the OH, rings, diols.' },
    { id: 'l05.dehydration', title: 'Dehydration (Zaitsev)', desc: 'Alcohol + H₂SO₄ → alkene + H₂O.' },
    { id: 'l05.oxidation', title: 'Oxidation of alcohols', desc: '1° → aldehyde → acid; 2° → ketone; 3° → no reaction.' },
    { id: 'l05.health', title: 'Alcohols in the body', desc: 'Ethanol & methanol metabolism; interesting alcohols.' },
  ],
  sections: [
    {
      id: 'families',
      title: 'Four families: alcohols, ethers, alkyl halides, thiols',
      minutes: 3,
      blocks: [
        { t: 'p', text: 'Chapter 14 covers four families that have a carbon **singly bonded** to O, S or a halogen:' },
        {
          t: 'mols', items: [
            { smiles: 'CCO', caption: 'alcohol: –OH (hydroxyl)' }, { smiles: 'CCOCC', caption: 'ether: C–O–C' },
            { smiles: 'CCCl', caption: 'alkyl halide: C–X' }, { smiles: 'CCS', caption: 'thiol: –SH (sulfhydryl)' },
          ],
        },
        { t: 'p', text: 'This lecture is about alcohols; Lecture 6 covers the other three.' },
      ],
    },
    {
      id: 'structure',
      title: 'Structure & classification',
      minutes: 6,
      blocks: [
        { t: 'p', text: 'Alcohols are classified by the **number of carbons bonded to the carbon that holds the OH** — the same idea as 1°/2°/3° carbons in Lecture 3.' },
        {
          t: 'mols', items: [
            { smiles: 'CCCO', caption: '1° alcohol: OH carbon bonded to 1 C', highlight: [2] },
            { smiles: 'CC(O)C', caption: '2° alcohol: OH carbon bonded to 2 C', highlight: [1] },
            { smiles: 'CC(C)(C)O', caption: '3° alcohol: OH carbon bonded to 3 C', highlight: [1] },
          ],
        },
        { t: 'callout', kind: 'warn', title: 'Count carbons on the OH carbon — not the OH itself', text: 'Find the carbon with the –OH first, then count only the **carbons** attached to it.' },
      ],
    },
    {
      id: 'properties',
      title: 'Physical properties',
      minutes: 6,
      blocks: [
        { t: 'list', items: ['The O is **bent** (like water), bond angle ~109.5°.', 'Two polar bonds (C–O and O–H) on a bent O → a **net dipole** (polar).', 'The O–H lets alcohols **hydrogen bond** to each other.'] },
        { t: 'callout', kind: 'key', title: 'Result', text: 'Alcohols have **much stronger intermolecular forces** than alkanes and alkenes → **higher boiling and melting points** than hydrocarbons of similar size.' },
        { t: 'table', head: ['Compound', 'Formula', 'bp'], rows: [['propane', '$CH_3CH_2CH_3$', '−42 °C'], ['ethanol', '$CH_3CH_2OH$', '78 °C']] },
        { t: 'h', text: 'Solubility' },
        { t: 'list', items: ['Alcohols dissolve in organic solvents.', '**Small** alcohols (up to about 5 C) **dissolve in water** — the O–H hydrogen bonds with water.', '**Larger** alcohols (6+ C) are **insoluble** — the nonpolar chain wins.'] },
        { t: 'mols', items: [{ smiles: 'CCO', caption: 'ethanol (2 C): water soluble' }, { smiles: 'CCCCCCCCO', caption: '1-octanol (8 C): water insoluble' }] },
        { t: 'callout', kind: 'exam', title: 'About the cutoff', text: 'The slides put the cutoff "around 6 carbons." Exam questions use clear-cut cases like **2 C (soluble)** vs **8 C (insoluble)**, so focus on the idea: a longer nonpolar chain makes it less soluble.' },
      ],
    },
    {
      id: 'naming',
      title: 'Naming alcohols',
      minutes: 9,
      blocks: [
        {
          t: 'steps', title: 'HOW TO name an alcohol', items: [
            'Find the **longest chain containing the carbon bonded to the OH**. Change the -e of the alkane to **-ol** (hexane → hexanol).',
            '**Number the chain to give the OH the lower number**, then apply all the other rules (substituents, alphabetical order).',
          ],
        },
        {
          t: 'example', title: 'Example', prompt: 'Name this alcohol.',
          mol: { smiles: 'CCC(C)CC(C)O', numbers: 'auto', name: '4-methyl-2-hexanol' },
          steps: ['Longest chain with the OH carbon: 6 C → hexan**ol**.', 'Number from the right so the OH is on **C2** (not C5).', 'Methyl on C4.'],
          answer: '**4-methyl-2-hexanol**',
        },
        {
          t: 'example', title: 'Practice from class', prompt: 'Draw 2,2-dimethyl-3-decanol.',
          steps: ['Parent: 3-dec**anol** → 10 carbons, OH on C3.', 'Two methyls on C2.'],
          mol: { smiles: 'CC(C)(C)C(O)CCCCCCC', numbers: 'auto', name: '2,2-dimethyl-3-decanol' },
          answer: '$CH_3C(CH_3)_2CH(OH)CH_2CH_2CH_2CH_2CH_2CH_2CH_3$',
        },
        { t: 'h', text: 'Rings and multiple OH groups' },
        { t: 'list', items: ['OH on a ring → the OH carbon is **C1** (the "1" is left out); then number to give the next substituent the lowest number.', 'Two OH groups → **diol** (or glycol); three → **triol**. Keep the "e": ethane**diol**.'] },
        {
          t: 'mols', items: [
            { smiles: 'CC1CCCCC1O', caption: '2-methylcyclohexanol', numbers: 'auto', name: '2-methylcyclohexanol' },
            { smiles: 'OCCO', caption: '1,2-ethanediol (ethylene glycol)', name: '1,2-ethanediol' },
            { smiles: 'OC1CCCC1O', caption: '1,2-cyclopentanediol', name: '1,2-cyclopentanediol' },
          ],
        },
        {
          t: 'check', q: {
            id: 'l05-c-name', skill: 'l05.naming', type: 'name', prompt: 'Name this alcohol.',
            figure: { smiles: 'CC(O)CCCCC' }, name: { smiles: 'CC(O)CCCCC' },
            explain: '7 carbons with OH on C2 → **2-heptanol**.',
          },
        },
      ],
    },
    {
      id: 'interesting',
      title: 'Interesting alcohols',
      minutes: 5,
      blocks: [
        {
          t: 'table', head: ['Alcohol', 'Formula', 'Fact'],
          rows: [
            ['**2-propanol** (isopropyl alcohol)', '$(CH_3)_2CHOH$', 'rubbing alcohol; sterilizes skin and instruments'],
            ['**ethanol**', '$CH_3CH_2OH$', 'in alcoholic drinks; made by **fermentation** of carbohydrates'],
            ['**methanol**', '$CH_3OH$', 'solvent / starting material for plastics; **toxic** (oxidized in the liver)'],
            ['**ethylene glycol** (a diol)', '$HOCH_2CH_2OH$', 'antifreeze; sweet-tasting but **extremely toxic**'],
            ['**glycerol** (a triol)', '$HOCH_2CH(OH)CH_2OH$', 'lotions, soap, shaving cream; sweet and **nontoxic** (used in food)'],
          ],
        },
        { t: 'p', text: '**Carbohydrates** are long, alcohol-rich natural polymers made mostly by plants. **Starch** (seeds, roots) is digested by humans into glucose; **cellulose** (wood, cotton) gives plants rigidity but humans **can\'t** digest it.' },
        { t: 'mol', smiles: 'OCC(O)C(O)C(O)C(O)C=O', caption: 'glucose (open-chain form): five OH groups' },
      ],
    },
    {
      id: 'dehydration',
      title: 'Reaction 1: Dehydration',
      minutes: 7,
      blocks: [
        { t: 'p', text: '**Dehydration** is the loss of $H_2O$. An alcohol treated with a strong acid ($H_2SO_4$) loses its OH and an H from a **neighboring** carbon, forming an **alkene**. This is an **elimination reaction** — atoms are "lost" and a multiple bond forms.' },
        { t: 'rxn', from: 'CCO', reagent: 'H₂SO₄', to: 'C=C', caption: 'ethanol → ethylene + H₂O' },
        { t: 'h', text: 'Zaitsev\'s rule' },
        { t: 'p', text: 'If the OH carbon has two different neighbors with H\'s, two alkenes can form. The major product follows **Zaitsev\'s rule**:' },
        { t: 'callout', kind: 'key', title: 'Zaitsev\'s rule', text: 'The **major** product is the alkene with **more alkyl (carbon) groups bonded to the C=C** — the more substituted alkene.' },
        { t: 'rxn', from: 'CC(O)CC', reagent: 'H₂SO₄', to: ['CC=CC', 'C=CCC'], caption: '2-butanol → 2-butene (major, 2 carbon groups on C=C) + 1-butene (minor, 1 carbon group)' },
        { t: 'callout', kind: 'memory', title: 'Don\'t mix them up', text: '**Markovnikov** (Lecture 4) is about **adding** HX/H₂O to an alkene. **Zaitsev** is about **making** an alkene by removing H₂O. Opposite directions!' },
      ],
    },
    {
      id: 'oxidation',
      title: 'Reaction 2: Oxidation',
      minutes: 9,
      blocks: [
        { t: 'callout', kind: 'key', title: 'Oxidation (organic definition)', text: '**More C–O bonds** or **fewer C–H bonds**. The symbol **[O]** means an oxidizing agent was added (commonly $K_2Cr_2O_7$).' },
        {
          t: 'table', head: ['Alcohol', 'H on the OH carbon?', 'Product with [O]'],
          rows: [
            ['**1°**', '2 H', '**aldehyde** → further oxidized to a **carboxylic acid**'],
            ['**2°**', '1 H', '**ketone** (stops here)'],
            ['**3°**', '0 H', '**no reaction**'],
          ],
        },
        { t: 'rxn', from: 'CCCO', reagent: '[O]', to: 'CCC=O', caption: '1° alcohol → aldehyde (replaces 1 C–H with 1 C–O)' },
        { t: 'rxn', from: 'CCC=O', reagent: '[O]', to: 'CCC(=O)O', caption: 'aldehyde → carboxylic acid (again 1 C–H → 1 C–O)' },
        { t: 'rxn', from: 'CC(O)CC', reagent: '[O]', to: 'CC(=O)CC', caption: '2° alcohol → ketone' },
        { t: 'callout', kind: 'tip', title: 'How to draw the product', text: 'Draw the full structure with the H\'s on the OH carbon. Remove **one H from that carbon** (and the H from O), and make the C=O. If the carbon has **no H** (3°), nothing can happen.' },
        {
          t: 'check', q: {
            id: 'l05-c-ox', skill: 'l05.oxidation', type: 'struct', prompt: 'Predict the product of oxidizing cyclohexanol ([O]).',
            figure: { rxn: { from: 'OC1CCCCC1', reagent: '[O]' } },
            choices: [{ smiles: 'O=C1CCCCC1' }, { smiles: 'C1=CCCCC1' }, { text: 'No reaction' }, { smiles: 'OC(=O)CCCCC' }], answer: 0,
            explain: 'Cyclohexanol is a **2° alcohol** (OH carbon bonded to 2 C) → **ketone** (cyclohexanone).',
          },
        },
      ],
    },
    {
      id: 'metabolism',
      title: 'Focus on health: metabolism of ethanol & methanol',
      minutes: 5,
      blocks: [
        { t: 'p', text: 'Ethanol is quickly absorbed in the stomach and small intestine. In the liver, the enzymes **alcohol dehydrogenase** and **aldehyde dehydrogenase** act as oxidizing agents — the same 1° alcohol → aldehyde → acid pathway:' },
        { t: 'rxn', from: 'CCO', reagent: '[O]', to: 'CC=O', caption: 'ethanol → acetaldehyde' },
        { t: 'rxn', from: 'CC=O', reagent: '[O]', to: 'CC(=O)O', caption: 'acetaldehyde → acetic acid' },
        { t: 'p', text: 'Drinking more ethanol than the liver can process builds up **acetaldehyde**, which is toxic (hangover symptoms).' },
        { t: 'rxn', from: 'CO', reagent: '[O]', to: 'C=O', caption: 'methanol → formaldehyde' },
        { t: 'rxn', from: 'C=O', reagent: '[O]', to: 'OC=O', caption: 'formaldehyde → formic acid' },
        { t: 'callout', kind: 'warn', title: 'Why methanol is deadly', text: 'The same enzymes turn methanol into **formaldehyde** and **formic acid** — both extremely toxic. Methanol poisoning lowers blood pH and causes **blindness** and **death**.' },
      ],
    },
  ],
  questions: [
    { id: 'l05-q01', skill: 'l05.classify', type: 'mc', prompt: 'How are alcohols classified as 1°, 2° or 3°?', choices: ['By the number of carbons bonded to the carbon holding the OH', 'By the number of OH groups', 'By the length of the chain', 'By the number of H on the oxygen'], answer: 0, explain: 'Count the **carbons** attached to the OH carbon.' },
    { id: 'l05-q02', skill: 'l05.classify', type: 'mc', prompt: '2-methyl-2-propanol, $(CH_3)_3COH$, is a…', choices: ['3° alcohol', '2° alcohol', '1° alcohol', 'diol'], answer: 0, explain: 'The OH carbon is bonded to **three** CH₃ groups → **tertiary**.' },
    { id: 'l05-q03', skill: 'l05.properties', type: 'mc', prompt: 'Why does ethanol (bp 78 °C) boil so much higher than propane (bp −42 °C)?', choices: ['Ethanol molecules hydrogen bond to each other', 'Ethanol is much heavier', 'Propane is ionic', 'Ethanol has a C=C bond'], answer: 0, explain: 'The **O–H** lets ethanol hydrogen bond — much stronger than propane\'s London forces.' },
    { id: 'l05-q04', skill: 'l05.properties', type: 'mc', prompt: 'Which alcohol is **least** soluble in water?', choices: ['1-octanol', 'methanol', 'ethanol', '1-propanol'], answer: 0, explain: 'The long 8-carbon chain of 1-octanol is too nonpolar.' },
    { id: 'l05-q05', skill: 'l05.properties', type: 'mc', prompt: 'What is the shape around the oxygen of an alcohol?', choices: ['bent', 'linear', 'trigonal planar', 'tetrahedral with 4 atoms'], answer: 0, explain: 'Two atoms + two lone pairs → **bent** (like water), ~109.5°.' },
    { id: 'l05-q06', skill: 'l05.naming', type: 'mc', prompt: 'When naming an alcohol, the chain is numbered to give the lowest number to…', choices: ['the carbon bearing the OH', 'the first alkyl branch', 'the longest branch', 'whichever end is on the left'], answer: 0, explain: 'The **OH** gets priority over alkyl substituents.' },
    { id: 'l05-q07', skill: 'l05.naming', type: 'name', prompt: 'Name this alcohol.', figure: { smiles: 'OC1CCCCC1' }, name: { smiles: 'OC1CCCCC1' }, explain: 'OH on a 6-membered ring, no other groups → **cyclohexanol** (no number needed).' },
    { id: 'l05-q08', skill: 'l05.naming', type: 'name', prompt: 'Name this alcohol.', figure: { smiles: 'CC(C)CC(C)O' }, name: { smiles: 'CC(C)CC(C)O' }, explain: '5-carbon chain; OH gets the lower number (C2); methyl on C4 → **4-methyl-2-pentanol**.' },
    { id: 'l05-q09', skill: 'l05.dehydration', type: 'mc', prompt: 'Dehydration of an alcohol requires…', choices: ['a strong acid such as H₂SO₄', 'H₂ and Pd', '[O] (K₂Cr₂O₇)', 'NaOH'], answer: 0, explain: 'Alcohol + **H₂SO₄** → alkene + H₂O.' },
    { id: 'l05-q10', skill: 'l05.dehydration', type: 'mc', prompt: 'Dehydration is an example of which kind of reaction?', choices: ['elimination', 'addition', 'substitution', 'reduction'], answer: 0, explain: 'Atoms (H and OH) are **eliminated** and a C=C forms.' },
    { id: 'l05-q11', skill: 'l05.dehydration', type: 'mc', prompt: 'Zaitsev\'s rule says the major alkene product is the one with…', choices: ['the most carbon groups on the C=C', 'the fewest carbon groups on the C=C', 'the C=C at the end of the chain', 'the OH still attached'], answer: 0, explain: 'The **more substituted** alkene (more alkyl groups on the C=C) is major.' },
    { id: 'l05-q12', skill: 'l05.oxidation', type: 'match', prompt: 'Match each alcohol with its oxidation outcome.', left: ['1° alcohol', '2° alcohol', '3° alcohol'], right: ['aldehyde, then carboxylic acid', 'ketone', 'no reaction'], answer: [0, 1, 2], explain: '1° → aldehyde → acid · 2° → ketone · 3° → no reaction (no H on the OH carbon).' },
    { id: 'l05-q13', skill: 'l05.oxidation', type: 'mc', prompt: 'Why can\'t a 3° alcohol be oxidized?', choices: ['The OH carbon has no H to lose', 'It has no oxygen', 'It is too large', '3° alcohols are ionic'], answer: 0, explain: 'Oxidation needs to replace a **C–H** on the OH carbon with a C–O bond. A 3° carbon has none.' },
    { id: 'l05-q14', skill: 'l05.oxidation', type: 'mc', prompt: 'In organic chemistry, oxidation means…', choices: ['more C–O bonds or fewer C–H bonds', 'more C–H bonds', 'losing oxygen', 'adding H₂'], answer: 0, explain: 'Oxidation = **gain C–O / lose C–H**.' },
    { id: 'l05-q15', skill: 'l05.health', type: 'order', prompt: 'Put the metabolism of ethanol in order.', items: ['acetic acid', 'ethanol', 'acetaldehyde'], answer: [1, 2, 0], explain: '**Ethanol → acetaldehyde → acetic acid** (by alcohol dehydrogenase, then aldehyde dehydrogenase).' },
    { id: 'l05-q16', skill: 'l05.health', type: 'mc', prompt: 'Methanol is so toxic because the liver oxidizes it to…', choices: ['formaldehyde and formic acid', 'ethanol and acetic acid', 'carbon dioxide only', 'glucose'], answer: 0, explain: 'Methanol → **formaldehyde** → **formic acid**, both very toxic (blindness, low blood pH, death).' },
    { id: 'l05-q17', skill: 'l05.health', type: 'mc', prompt: 'Which alcohol is sweet, nontoxic and used in food, lotions and soap?', choices: ['glycerol', 'ethylene glycol', 'methanol', '2-propanol'], answer: 0, explain: '**Glycerol** (a triol). Ethylene glycol is also sweet but extremely toxic.' },
    { id: 'l05-q18', skill: 'l05.health', type: 'tf', prompt: 'True or false: humans can digest cellulose into glucose.', answer: false, explain: '**False.** Humans digest **starch** but not **cellulose** (wood, cotton).' },
  ],
  cards: [
    { id: 'l05-k01', front: 'Alcohol functional group', back: '**–OH** (hydroxyl) bonded to an sp³ carbon.' },
    { id: 'l05-k02', front: '1°, 2°, 3° alcohol', back: 'The OH carbon is bonded to **1, 2, or 3 carbons**.' },
    { id: 'l05-k03', front: 'Why do alcohols boil higher than alkanes?', back: 'The O–H lets them **hydrogen bond**; they are also polar.' },
    { id: 'l05-k04', front: 'Alcohol water solubility', back: 'Small alcohols dissolve; larger ones (≈6+ C) don\'t.' },
    { id: 'l05-k05', front: 'Alcohol naming suffix & numbering', back: '**-ol**; number so the **OH gets the lowest number**.' },
    { id: 'l05-k06', front: 'OH on a ring', back: 'The OH carbon is C1 (not written): e.g. **2-methylcyclohexanol**.' },
    { id: 'l05-k07', front: 'Diol / glycol', back: 'Two OH groups, e.g. **1,2-ethanediol** (ethylene glycol).' },
    { id: 'l05-k08', front: 'Dehydration', back: 'Alcohol + **H₂SO₄** → **alkene + H₂O** (elimination).' },
    { id: 'l05-k09', front: 'Zaitsev\'s rule', back: 'Major alkene = the one with **more carbon groups on the C=C**.' },
    { id: 'l05-k10', front: 'Oxidation of a 1° alcohol', back: '→ **aldehyde** → **carboxylic acid**' },
    { id: 'l05-k11', front: 'Oxidation of a 2° alcohol', back: '→ **ketone**' },
    { id: 'l05-k12', front: 'Oxidation of a 3° alcohol', back: '**No reaction** (no H on the OH carbon).' },
    { id: 'l05-k13', front: 'What does [O] mean?', back: 'An **oxidizing agent**, commonly $K_2Cr_2O_7$.' },
    { id: 'l05-k14', front: 'Ethanol metabolism', back: 'ethanol → **acetaldehyde** (toxic) → **acetic acid**' },
    { id: 'l05-k15', front: 'Methanol metabolism', back: 'methanol → **formaldehyde** → **formic acid** → blindness, acidosis, death' },
    { id: 'l05-k16', front: 'Rubbing alcohol', back: '**2-propanol** (isopropyl alcohol)' },
    { id: 'l05-k17', front: 'Antifreeze', back: '**Ethylene glycol** — sweet but extremely toxic.' },
    { id: 'l05-k18', front: 'Starch vs cellulose', back: 'Both glucose polymers. Humans digest **starch**, not **cellulose**.' },
  ],
  keyTerms: [
    { term: 'alcohol', def: 'A compound with an OH group on an sp³ carbon.' },
    { term: 'hydroxyl group', def: 'The –OH functional group.' },
    { term: 'diol', def: 'A compound with two OH groups (a glycol).' },
    { term: 'dehydration', def: 'Loss of H₂O from an alcohol to form an alkene (acid catalyst).' },
    { term: 'elimination reaction', def: 'A reaction in which atoms are removed and a multiple bond forms.' },
    { term: 'Zaitsev\'s rule', def: 'In dehydration, the major alkene has more alkyl groups on the C=C.' },
    { term: 'oxidation', def: 'Gain of C–O bonds or loss of C–H bonds.' },
    { term: 'fermentation', def: 'Conversion of carbohydrates to ethanol by yeast.' },
  ],
};
