// Lecture 6 — Ethers, Alkyl Halides & Thiols (Smith Ch. 14.7–14.10)
export default {
  id: 'l06',
  number: 6,
  title: 'Ethers, Halides & Thiols',
  subtitle: 'Structure, properties, naming & disulfides',
  chapter: 'Ch. 14.7–14.10',
  tested: false,
  summary: 'Three more single-bond families. Compare each to alcohols: ethers and alkyl halides are polar but can\'t H-bond; thiols smell bad and oxidize to disulfides.',
  skills: [
    { id: 'l06.properties', title: 'Properties & boiling points', desc: 'Where ethers, alkyl halides and thiols fall between alkanes and alcohols.' },
    { id: 'l06.ether-naming', title: 'Naming ethers', desc: 'Common names (ethyl methyl ether) and IUPAC alkoxy names.' },
    { id: 'l06.halide-class', title: 'Classifying alkyl halides', desc: '1°, 2°, 3° alkyl halides.' },
    { id: 'l06.halide-naming', title: 'Naming alkyl halides', desc: 'fluoro-, chloro-, bromo-, iodo- prefixes.' },
    { id: 'l06.thiol-naming', title: 'Naming thiols', desc: 'The -thiol suffix.' },
    { id: 'l06.thiols', title: 'Thiols & disulfides', desc: 'Odor, oxidation to disulfides, hair and proteins.' },
  ],
  sections: [
    {
      id: 'ethers',
      title: 'Ethers: structure & properties',
      minutes: 7,
      blocks: [
        { t: 'p', text: '**Ethers** have two alkyl groups bonded to an oxygen: R–O–R\'. The two groups can be the same or different.' },
        { t: 'mols', items: [{ smiles: 'CCOCC', caption: 'diethyl ether' }, { smiles: 'COCCC', caption: 'methyl propyl ether' }, { smiles: 'C1CO1', caption: 'an epoxide (3-membered ring)' }] },
        { t: 'list', items: ['The ether O is **bent** like water: ~109.5°.', 'An O can sit inside a ring — a ring containing a heteroatom is a **heterocycle**. A 3-membered ring ether is an **epoxide**.', 'Two polar C–O bonds on a bent O → a **net dipole**.', 'No H on the O → ether molecules **cannot hydrogen bond with each other**.'] },
        { t: 'callout', kind: 'key', title: 'Ethers sit in the middle', text: 'Compared with molecules of similar size, ethers have **stronger forces than alkanes** (they\'re polar) but **weaker forces than alcohols** (no O–H). So: **alkane < ether < alcohol** in boiling point.' },
        { t: 'table', head: ['Compound', 'Formula', 'bp'], rows: [['butane', '$CH_3CH_2CH_2CH_3$', '−0.5 °C'], ['diethyl ether', '$CH_3CH_2OCH_2CH_3$', '35 °C'], ['1-butanol', '$CH_3CH_2CH_2CH_2OH$', '118 °C']] },
        { t: 'h', text: 'Solubility' },
        { t: 'list', items: ['Ethers dissolve in organic solvents.', '**Small ethers (≤5 C) are water soluble** — water can hydrogen bond **to** the ether\'s O (the ether is an H-bond acceptor).', 'Ethers with **6 or more C** are insoluble.'] },
        { t: 'callout', kind: 'life', title: 'Ethers as anesthetics', text: 'Diethyl ether was first shown to work as a general anesthetic in **1846** by dentist William Morton. Before that, surgery patients had to endure the pain. Modern anesthetics (isoflurane, sevoflurane, desflurane) are **halogenated ethers**.' },
      ],
    },
    {
      id: 'ether-naming',
      title: 'Naming ethers',
      minutes: 7,
      blocks: [
        { t: 'h', text: 'Common names (simple ethers)' },
        { t: 'steps', items: ['Name **both alkyl groups** on the oxygen.', 'Put them in **alphabetical order**.', 'Add the word **ether**. (Two identical groups: **di**ethyl ether.)'] },
        { t: 'mols', items: [{ smiles: 'CCOC', caption: 'ethyl methyl ether', name: 'methoxyethane' }, { smiles: 'CCOCC', caption: 'diethyl ether', name: 'ethoxyethane' }, { smiles: 'CCOCCC', caption: 'ethyl propyl ether', name: '1-ethoxypropane' }] },
        { t: 'h', text: 'IUPAC names (more complex ethers)' },
        { t: 'steps', items: ['Name the **longer** chain as the alkane (parent).', 'Name the **shorter** chain + O as an **alkoxy** substituent: $CH_3O$– = **methoxy**, $CH_3CH_2O$– = **ethoxy**.', 'Number and alphabetize like any other substituent.'] },
        {
          t: 'example', title: 'Sample Problem 14.6 style', prompt: 'Give the IUPAC name.',
          mol: { smiles: 'CCC(OC)CCCC', numbers: 'auto', name: '3-methoxyheptane' },
          steps: ['Longer chain: 7 C → heptane. Shorter group: $OCH_3$ → methoxy.', 'Number to give the methoxy the lowest number: C3.'],
          answer: '**3-methoxyheptane**',
        },
        { t: 'callout', kind: 'tip', title: 'Common vs IUPAC', text: '$CH_3OCH_2CH_3$: common name **ethyl methyl ether**, IUPAC name **methoxyethane**. Both describe the same molecule.' },
      ],
    },
    {
      id: 'halides',
      title: 'Alkyl halides',
      minutes: 8,
      blocks: [
        { t: 'p', text: '**Alkyl halides** contain a halogen atom **X (F, Cl, Br, I)** bonded to carbon. Like alcohols, they are classified by the number of carbons on the carbon holding X:' },
        { t: 'mols', items: [{ smiles: 'CCCBr', caption: '1° (bonded to 1 C)', highlight: [2] }, { smiles: 'CC(Br)C', caption: '2° (bonded to 2 C)', highlight: [1] }, { smiles: 'CC(C)(C)Br', caption: '3° (bonded to 3 C)', highlight: [1] }] },
        { t: 'h', text: 'Properties' },
        { t: 'list', items: ['Polar C–X bond → a **net dipole**.', '**No** intermolecular hydrogen bonding.', 'So their bp is **higher than similar alkanes** but **lower than alcohols**.', 'Boiling point **increases** with the **size of the alkyl group** and the **size of the halogen** (F < Cl < Br < I).', '**All alkyl halides are insoluble in water.**'] },
        { t: 'h', text: 'Naming' },
        { t: 'steps', items: ['Find the parent chain **containing the carbon with the halogen**.', 'Name the halogen as a prefix: **fluoro, chloro, bromo, iodo**.', 'Number to give the substituents the lowest numbers; **alphabetize** halo and alkyl groups together.'] },
        {
          t: 'example', title: 'Example', prompt: 'Give the IUPAC name.',
          mol: { smiles: 'CC(Cl)CCC(C)CC', numbers: 'auto', name: '2-chloro-5-methylheptane' },
          steps: ['Parent: 7 C → heptane.', 'Number from the left: Cl on C2, methyl on C5 (from the right: C3 and C6).', 'Alphabetize: **c**hloro before **m**ethyl.'],
          answer: '**2-chloro-5-methylheptane**',
        },
        { t: 'mols', items: [{ smiles: 'ClCCCl', caption: '1,2-dichloroethane', name: '1,2-dichloroethane' }, { smiles: 'CC(Br)CCC(C)C', caption: '2-bromo-5-methylhexane', numbers: 'auto', name: '2-bromo-5-methylhexane' }] },
        { t: 'callout', kind: 'tip', title: 'Tie-breaker in action', text: 'In 2-bromo-5-methylhexane, both directions give {2, 5}, so the **alphabetically first** group (**b**romo) gets the lower number.' },
      ],
    },
    {
      id: 'thiols',
      title: 'Thiols',
      minutes: 8,
      blocks: [
        { t: 'p', text: '**Thiols** contain an **–SH (sulfhydryl)** group. Sulfur is right below oxygen in the periodic table, so thiols look like alcohols, with a **bent** shape around S.' },
        { t: 'callout', kind: 'key', title: 'But no hydrogen bonding', text: 'The S–H bond isn\'t polar enough, so thiols **can\'t hydrogen bond** → **lower boiling points than similar alcohols**: ethanol 78 °C vs ethanethiol 35 °C.' },
        { t: 'mols', items: [{ smiles: 'CCO', caption: 'ethanol, bp 78 °C' }, { smiles: 'CCS', caption: 'ethanethiol, bp 35 °C' }] },
        { t: 'p', text: 'Thiols have a strong, **foul odor** — skunk spray, onions, and the smell added to natural gas.' },
        { t: 'h', text: 'Naming' },
        { t: 'steps', items: ['Name the parent chain as an alkane (keep the -e).', 'Add the suffix **-thiol**.', 'Number to give the SH the lowest number.'] },
        { t: 'mols', items: [{ smiles: 'CS', caption: 'methanethiol', name: 'methanethiol' }, { smiles: 'CCCS', caption: '1-propanethiol', name: '1-propanethiol' }, { smiles: 'CCC(S)CCC', caption: '3-hexanethiol', numbers: 'auto', name: '3-hexanethiol' }] },
        { t: 'h', text: 'Oxidation to disulfides' },
        { t: 'p', text: 'Thiols are **oxidized** to **disulfides** (R–S–S–R). Remember, oxidation = more bonds to O **or fewer bonds to H** — each S loses its H. A **reducing agent [H]** turns the disulfide back into two thiols.' },
        { t: 'rxn', from: 'CCS', reagent: '[O]', to: 'CCSSCC', caption: '2 CH₃CH₂SH → CH₃CH₂S–SCH₂CH₃' },
        { t: 'rxn', from: 'CCSSCC', reagent: '[H]', to: 'CCS', caption: 'reduction gives back 2 thiols' },
        { t: 'callout', kind: 'life', title: 'Perms and proteins', text: 'Hair proteins are held in shape by **disulfide bonds**. A perm **reduces** them, the hair is wrapped on curlers, then an **oxidizing agent** re-forms the S–S bonds in new places → curls. Proteins like **insulin** also use disulfide bonds to keep their 3-D shape.' },
      ],
    },
  ],
  questions: [
    { id: 'l06-q01', skill: 'l06.properties', type: 'order', prompt: 'Rank by boiling point (lowest → highest), similar size: butane, diethyl ether, 1-butanol.', items: ['1-butanol', 'butane', 'diethyl ether'], answer: [1, 2, 0], explain: 'Alkane (London only) < ether (polar, no H-bond) < alcohol (H-bonds): −0.5 °C < 35 °C < 118 °C.' },
    { id: 'l06-q02', skill: 'l06.properties', type: 'mc', prompt: 'Why can\'t two ether molecules hydrogen bond with each other?', choices: ['There is no H bonded to the oxygen', 'Ethers have no lone pairs', 'Ethers are nonpolar', 'The O is linear'], answer: 0, explain: 'H-bonding needs an **H on O/N/F**. The ether O has lone pairs but no H.' },
    { id: 'l06-q03', skill: 'l06.properties', type: 'tf', prompt: 'True or false: diethyl ether (4 C) is somewhat soluble in water.', answer: true, explain: '**True.** Water H-bonds to the ether O; small ethers (≤5 C) dissolve.' },
    { id: 'l06-q04', skill: 'l06.properties', type: 'mc', prompt: 'Which alkyl halide has the **highest** boiling point?', choices: ['iodoethane', 'bromoethane', 'chloroethane', 'fluoroethane'], answer: 0, shuffle: false, explain: 'Bigger halogen → higher bp: F < Cl < Br < **I** (72 °C).' },
    { id: 'l06-q05', skill: 'l06.properties', type: 'tf', prompt: 'True or false: all alkyl halides are insoluble in water.', answer: true, explain: '**True** (as stated in class) — they can\'t hydrogen bond with water.' },
    { id: 'l06-q06', skill: 'l06.ether-naming', type: 'mc', prompt: 'What is the common name of $CH_3CH_2OCH_3$?', choices: ['ethyl methyl ether', 'methyl ethyl ether', 'propyl ether', 'dimethyl ether'], answer: 0, explain: 'Both groups in **alphabetical** order + ether: **e**thyl before **m**ethyl.' },
    { id: 'l06-q07', skill: 'l06.ether-naming', type: 'mc', prompt: 'In IUPAC naming of ethers, the $CH_3CH_2O$– group is called…', choices: ['ethoxy', 'ethyl', 'ethanol', 'ethyloxide'], answer: 0, explain: 'Alkyl + O as a substituent = **alkoxy**: methoxy, **ethoxy**, propoxy.' },
    { id: 'l06-q08', skill: 'l06.ether-naming', type: 'name', prompt: 'Give the IUPAC name.', figure: { smiles: 'CCC(OC)CCCC' }, name: { smiles: 'CCC(OC)CCCC' }, explain: 'Heptane with an OCH₃ on C3 → **3-methoxyheptane**.' },
    { id: 'l06-q09', skill: 'l06.halide-class', type: 'mc', prompt: '2-bromopropane, $CH_3CHBrCH_3$, is a…', choices: ['2° alkyl halide', '1° alkyl halide', '3° alkyl halide', 'dihalide'], answer: 0, explain: 'The C holding Br is bonded to **two** carbons → **secondary**.' },
    { id: 'l06-q10', skill: 'l06.halide-naming', type: 'name', prompt: 'Name this alkyl halide.', figure: { smiles: 'CC(Cl)CCC(C)CC' }, name: { smiles: 'CC(Cl)CCC(C)CC' }, explain: 'Heptane; Cl on C2, methyl on C5; alphabetical → **2-chloro-5-methylheptane**.' },
    { id: 'l06-q11', skill: 'l06.halide-naming', type: 'struct', prompt: 'Which structure is **1,2-dichloroethane**?', choices: [{ smiles: 'ClCCCl' }, { smiles: 'CC(Cl)Cl' }, { smiles: 'ClCCCCl' }, { smiles: 'CCCl' }], answer: 0, explain: 'Two carbons with one Cl on **each** carbon.' },
    { id: 'l06-q12', skill: 'l06.thiol-naming', type: 'name', prompt: 'Name this thiol.', figure: { smiles: 'CCC(S)CCC' }, name: { smiles: 'CCC(S)CCC' }, explain: 'Hexane + SH on C3 → **3-hexanethiol**.' },
    { id: 'l06-q13', skill: 'l06.thiol-naming', type: 'mc', prompt: 'Which is the correct name for $CH_3CH_2CH_2SH$?', choices: ['1-propanethiol', '1-propanol', 'propyl sulfide', '1-propthiol'], answer: 0, explain: 'Keep the -e of propane and add **-thiol**, with the SH on C1: **1-propanethiol**.' },
    { id: 'l06-q14', skill: 'l06.thiols', type: 'mc', prompt: 'Why does ethanethiol (bp 35 °C) boil lower than ethanol (bp 78 °C)?', choices: ['Thiols can\'t hydrogen bond', 'Sulfur is lighter than oxygen', 'Thiols are ionic', 'Ethanethiol has a double bond'], answer: 0, explain: 'The S–H bond isn\'t polar enough for **hydrogen bonding**.' },
    { id: 'l06-q15', skill: 'l06.thiols', type: 'mc', prompt: 'Oxidizing two thiol molecules produces a…', choices: ['disulfide (R–S–S–R)', 'sulfide (R–S–R)', 'alcohol', 'thioether'], answer: 0, explain: '2 R–SH → **R–S–S–R** (each S loses an H).' },
    { id: 'l06-q16', skill: 'l06.thiols', type: 'order', prompt: 'Put the steps of a hair perm in order.', items: ['apply an oxidizing agent to re-form S–S bonds', 'wrap hair around curlers', 'reduce the disulfide bonds'], answer: [2, 1, 0], explain: '**Reduce** S–S bonds → **reshape** on curlers → **oxidize** to lock the new S–S bonds.' },
    { id: 'l06-q17', skill: 'l06.properties', type: 'mc', prompt: 'A 3-membered ring containing an oxygen is called…', choices: ['an epoxide', 'an ester', 'a cycloether ketone', 'a lactone'], answer: 0, explain: 'A 3-membered cyclic ether is an **epoxide** (a type of heterocycle).' },
  ],
  cards: [
    { id: 'l06-k01', front: 'Ether', back: 'R–O–R\': an O bonded to two carbons.' },
    { id: 'l06-k02', front: 'Shape around the ether O', back: '**Bent**, ~109.5°.' },
    { id: 'l06-k03', front: 'Heterocycle / epoxide', back: 'Heterocycle = ring with a heteroatom. **Epoxide** = 3-membered ring ether.' },
    { id: 'l06-k04', front: 'Ether boiling points', back: 'Higher than alkanes (polar), **lower than alcohols** (no O–H, no H-bonding between ethers).' },
    { id: 'l06-k05', front: 'Ether water solubility', back: '≤5 C: soluble (water H-bonds to the O). 6+ C: insoluble.' },
    { id: 'l06-k06', front: 'Common ether names', back: 'Both alkyl groups, **alphabetical**, + "ether": ethyl methyl ether, diethyl ether.' },
    { id: 'l06-k07', front: 'IUPAC ether names', back: 'Longer chain = parent; shorter + O = **alkoxy** (methoxy, ethoxy): 3-methoxyheptane.' },
    { id: 'l06-k08', front: 'First ether anesthetic', back: '**Diethyl ether**, 1846, dentist William Morton.' },
    { id: 'l06-k09', front: 'Alkyl halide bp trends', back: 'Increases with **size of the alkyl group** and **size of the halogen** (F < Cl < Br < I).' },
    { id: 'l06-k10', front: 'Alkyl halide solubility', back: '**All** alkyl halides are insoluble in water.' },
    { id: 'l06-k11', front: 'Halogen prefixes', back: '**fluoro, chloro, bromo, iodo** — alphabetized with alkyl groups.' },
    { id: 'l06-k12', front: 'Thiol', back: 'R–SH (sulfhydryl group). Bent at S. Foul odor.' },
    { id: 'l06-k13', front: 'Thiol vs alcohol boiling point', back: 'Thiols are lower (no H-bonding): ethanethiol 35 °C vs ethanol 78 °C.' },
    { id: 'l06-k14', front: 'Thiol naming', back: 'Alkane name + **-thiol**: 1-propanethiol.' },
    { id: 'l06-k15', front: 'Thiol oxidation', back: '2 R–SH **[O]** → **R–S–S–R** (disulfide). Reduction [H] reverses it.' },
    { id: 'l06-k16', front: 'Disulfides in biology', back: 'Hold proteins (insulin, hair keratin) in shape; perms break and re-form them.' },
  ],
  keyTerms: [
    { term: 'ether', def: 'A compound with two alkyl groups bonded to an oxygen (R–O–R).' },
    { term: 'alkoxy group', def: 'An alkyl group bonded through oxygen, used as a substituent (methoxy, ethoxy).' },
    { term: 'heterocycle', def: 'A ring that contains a heteroatom.' },
    { term: 'epoxide', def: 'A three-membered ring ether.' },
    { term: 'alkyl halide', def: 'A compound with a halogen bonded to an sp³ carbon.' },
    { term: 'thiol', def: 'A compound with an –SH (sulfhydryl) group.' },
    { term: 'disulfide', def: 'A compound with an S–S bond, formed by oxidizing thiols.' },
  ],
};
