// Lecture 8 — Aldehydes & Ketones (Smith Ch. 16.1–16.6)
export default {
  id: 'l08',
  number: 8,
  title: 'Aldehydes & Ketones',
  subtitle: 'The carbonyl group: naming, properties, oxidation & reduction',
  chapter: 'Ch. 16.1–16.6',
  tested: false,
  summary: 'Aldehydes (–CHO) and ketones (C=O between two carbons): naming with -al and -one, where they sit on the boiling-point ladder, and how they oxidize and reduce (the reverse of alcohol oxidation).',
  skills: [
    { id: 'l08.structure', title: 'Structure of the carbonyl', desc: 'Aldehyde vs ketone; trigonal planar, polar C=O.' },
    { id: 'l08.naming', title: 'Naming aldehydes & ketones', desc: '-al (C1, no number) and -one; common names.' },
    { id: 'l08.properties', title: 'Physical properties', desc: 'bp between alkanes and alcohols; solubility.' },
    { id: 'l08.reactions', title: 'Oxidation & reduction', desc: 'Aldehyde → acid; ketones don\'t oxidize; reduction to 1°/2° alcohols.' },
    { id: 'l08.health', title: 'Interesting aldehydes & ketones', desc: 'Formaldehyde, acetone, ketoacidosis, flavors, NADH.' },
  ],
  sections: [
    {
      id: 'structure',
      title: 'Structure and bonding',
      minutes: 6,
      blocks: [
        { t: 'p', text: 'Aldehydes and ketones both contain a **carbonyl group (C=O)** with only **C and H** attached to the carbonyl carbon:' },
        {
          t: 'compare', items: [
            { title: 'Aldehyde (RCHO)', text: 'At least **one H** on the carbonyl carbon. Always at the **end** of a chain.' },
            { title: 'Ketone (RCOR)', text: '**Two carbons** on the carbonyl carbon. Always **inside** a chain or ring.' },
          ],
        },
        { t: 'mols', items: [{ smiles: 'CC=O', caption: 'acetaldehyde (an aldehyde)' }, { smiles: 'CC(C)=O', caption: 'acetone (a ketone)' }] },
        { t: 'p', text: 'Carboxylic acids, esters and amides also have C=O, but with an **O or N** on the carbonyl carbon — they\'re different families (Lectures 2 and 10).' },
        { t: 'list', items: ['The carbonyl carbon is **trigonal planar**: bond angles **120°**.', 'O is more electronegative than C, so the C=O is **polar**: O is electron-rich (**δ−**) and the carbonyl C is electron-poor (**δ+**).'] },
      ],
    },
    {
      id: 'naming',
      title: 'Naming aldehydes & ketones',
      minutes: 10,
      blocks: [
        { t: 'h', text: 'Aldehydes: -al' },
        { t: 'steps', items: ['Find the longest chain **containing the CHO** carbon.', 'Change -e of the alkane to **-al**.', 'The CHO carbon is **C1** — so no number is needed for it.', 'Number and name substituents as usual.'] },
        { t: 'mols', items: [{ smiles: 'CCCC=O', caption: 'butanal', numbers: 'auto', name: 'butanal' }, { smiles: 'CCCCC(C)C=O', caption: '2-methylhexanal', numbers: 'auto', name: '2-methylhexanal' }, { smiles: 'CCC(C=O)C(C)C', caption: '2-ethyl-3-methylbutanal', numbers: 'auto', name: '2-ethyl-3-methylbutanal' }] },
        { t: 'p', text: '**Common names** use "-aldehyde":' },
        { t: 'mols', items: [{ smiles: 'C=O', caption: 'formaldehyde (methanal)' }, { smiles: 'CC=O', caption: 'acetaldehyde (ethanal)' }, { smiles: 'O=Cc1ccccc1', caption: 'benzaldehyde' }] },
        { t: 'h', text: 'Ketones: -one' },
        { t: 'steps', items: ['Find the longest chain **containing the C=O** carbon.', 'Change -e to **-one**.', 'Number to give the **carbonyl carbon the lower number**.', 'Apply all other rules.'] },
        { t: 'mols', items: [{ smiles: 'CC(C)=O', caption: '2-propanone (acetone)', name: '2-propanone' }, { smiles: 'CCC(C)=O', caption: '2-butanone', numbers: 'auto', name: '2-butanone' }, { smiles: 'CC(C)CC(C)=O', caption: '4-methyl-2-pentanone', numbers: 'auto', name: '4-methyl-2-pentanone' }] },
        { t: 'p', text: 'In a ring, the carbonyl carbon is **C1**:' },
        { t: 'mols', items: [{ smiles: 'O=C1CCCCC1', caption: 'cyclohexanone', name: 'cyclohexanone' }, { smiles: 'O=C1C(C)C(CC)CC1', caption: '3-ethyl-2-methylcyclopentanone', numbers: 'auto', name: '3-ethyl-2-methylcyclopentanone' }] },
        { t: 'p', text: '**Common names** of ketones: name both alkyl groups alphabetically + **ketone** (just like ethers): $CH_3COCH_2CH_3$ = **ethyl methyl ketone**.' },
        { t: 'callout', kind: 'warn', title: 'Aldehyde or ketone?', text: 'A C=O at the **end** of a chain is always an aldehyde. "1-butanone" doesn\'t exist — that\'s butanal.' },
        {
          t: 'check', q: {
            id: 'l08-c-name', skill: 'l08.naming', type: 'name', prompt: 'Name this aldehyde.',
            figure: { smiles: 'CCCCC(C)C=O' }, name: { smiles: 'CCCCC(C)C=O' },
            explain: 'Six carbons including the CHO (C1); methyl on C2 → **2-methylhexanal**.',
          },
        },
      ],
    },
    {
      id: 'properties',
      title: 'Physical properties',
      minutes: 6,
      blocks: [
        { t: 'callout', kind: 'key', title: 'The boiling-point ladder', text: '**alkanes < aldehydes & ketones < alcohols** (similar size)\n- Higher than alkanes: polar C=O → dipole–dipole forces.\n- Lower than alcohols: **no O–H**, so no hydrogen bonding between molecules.' },
        { t: 'table', head: ['Compound', 'Family', 'bp'], rows: [['pentane', 'alkane', '36 °C'], ['butanal', 'aldehyde', '76 °C'], ['2-butanone', 'ketone', '80 °C'], ['1-butanol', 'alcohol', '118 °C']] },
        { t: 'list', items: ['Soluble in organic solvents.', 'With **6 or fewer C**: **water soluble** (water H-bonds to the C=O oxygen).', 'With **7 or more C**: **insoluble**.'] },
      ],
    },
    {
      id: 'interesting',
      title: 'Interesting aldehydes & ketones',
      minutes: 5,
      blocks: [
        { t: 'list', items: ['**Formaldehyde** ($CH_2=O$), the simplest aldehyde: used to make resins and plastics; sold as **formalin** (37% in water) to preserve biological specimens.', '**Acetone** ($(CH_3)_2C=O$), the simplest ketone: industrial solvent (nail polish remover). Ketones are also made when the body breaks down fatty acids — unusually high levels in diabetic patients cause **diabetic ketoacidosis**.'] },
        {
          t: 'mols', items: [
            { smiles: 'O=C/C=C/c1ccccc1', caption: 'cinnamaldehyde (cinnamon)' },
            { smiles: 'COc1cc(C=O)ccc1O', caption: 'vanillin (vanilla)' },
            { smiles: 'CC(C)=CCC/C(C)=C/C=O', caption: 'citral (lemongrass)' },
            { smiles: 'CC(C)=CCCC(C)CC=O', caption: 'citronellal (citronella candles)' },
          ],
        },
      ],
    },
    {
      id: 'oxidation',
      title: 'Reactions: oxidation',
      minutes: 6,
      blocks: [
        { t: 'callout', kind: 'key', title: 'Remember', text: '**Oxidation** = more bonds to O, or fewer bonds to H.' },
        { t: 'p', text: 'In oxidation, the **aldehyde C–H** bond becomes a **C–OH** bond: aldehydes are oxidized to **carboxylic acids**.' },
        { t: 'rxn', from: 'CCC=O', reagent: '[O]', to: 'CCC(=O)O', caption: 'propanal → propanoic acid' },
        { t: 'p', text: '**Ketones cannot be oxidized** — the carbonyl carbon has no C–H bond.' },
        { t: 'rxn', from: 'CC(C)=O', reagent: '[O]', to: [], caption: 'acetone + [O] → no reaction' },
        { t: 'callout', kind: 'tip', title: 'Connect it to Lecture 5', text: '1° alcohol → **aldehyde** → carboxylic acid. 2° alcohol → **ketone** → stops. Same chemistry, one step later.' },
      ],
    },
    {
      id: 'reduction',
      title: 'Reactions: reduction',
      minutes: 7,
      blocks: [
        { t: 'callout', kind: 'key', title: 'Reduction', text: 'The opposite of oxidation: **fewer C–O bonds** or **more C–H bonds**. Here: H₂ adds across the C=O (with a Pd catalyst).' },
        {
          t: 'table', head: ['Starting compound', '+ H₂, Pd', 'Reverse ([O])'],
          rows: [['**aldehyde**', '→ **1° alcohol**', '1° alcohol → aldehyde'], ['**ketone**', '→ **2° alcohol**', '2° alcohol → ketone']],
        },
        { t: 'rxn', from: 'CCC=O', reagent: 'H₂, Pd', to: 'CCCO', caption: 'propanal → 1-propanol (1° alcohol)' },
        { t: 'rxn', from: 'CCC(C)=O', reagent: 'H₂, Pd', to: 'CCC(C)O', caption: '2-butanone → 2-butanol (2° alcohol)' },
        { t: 'p', text: 'Carbonyl reduction is used in real drug synthesis — for example, a step in making **Prozac**.' },
        { t: 'callout', kind: 'life', title: 'In your body', text: 'Cells don\'t have H₂ and Pd. Instead they use the coenzyme **NADH** (with an enzyme) as the reducing agent. When NADH reduces something it is oxidized to **NAD⁺**, which is itself a biological oxidizing agent.' },
        {
          t: 'check', q: {
            id: 'l08-c-red', skill: 'l08.reactions', type: 'mc', prompt: 'Reducing a ketone gives a…',
            choices: ['2° alcohol', '1° alcohol', 'carboxylic acid', 'no reaction'], answer: 0, shuffle: false,
            explain: 'The C=O carbon keeps its two carbon groups and gains an H and OH → **2° alcohol**.',
          },
        },
      ],
    },
  ],
  questions: [
    { id: 'l08-q01', skill: 'l08.structure', type: 'mc', prompt: 'What is the bond angle around a carbonyl carbon?', choices: ['120°', '109.5°', '180°', '90°'], answer: 0, shuffle: false, explain: 'Three groups around the C (the C=O counts once) → **trigonal planar, 120°**.' },
    { id: 'l08-q02', skill: 'l08.structure', type: 'mc', prompt: 'In a C=O bond, which atom carries the partial positive charge (δ+)?', choices: ['carbon', 'oxygen', 'neither', 'both'], answer: 0, explain: 'O is more electronegative, so O is δ− and the **carbon is δ+**.' },
    { id: 'l08-q03', skill: 'l08.structure', type: 'mc', prompt: 'Which is an aldehyde?', choices: ['$CH_3CH_2CHO$', '$CH_3COCH_3$', '$CH_3COOH$', '$CH_3CH_2OH$'], answer: 0, explain: '**CHO** = aldehyde; CO in the middle = ketone; COOH = acid; OH = alcohol.' },
    { id: 'l08-q04', skill: 'l08.naming', type: 'mc', prompt: 'Why is there no number in the name "2-methylbutanal" for the aldehyde group?', choices: ['The CHO carbon is always C1', 'Aldehydes are never numbered', 'Methyl gets the priority', 'It is optional'], answer: 0, explain: 'The CHO carbon is **always C1**, so its number is understood.' },
    { id: 'l08-q05', skill: 'l08.naming', type: 'name', prompt: 'Name this ketone.', figure: { smiles: 'CCC(C)=O' }, name: { smiles: 'CCC(C)=O' }, explain: 'Four carbons, C=O on C2 → **2-butanone** (also called ethyl methyl ketone).' },
    { id: 'l08-q06', skill: 'l08.naming', type: 'name', prompt: 'Name this ketone.', figure: { smiles: 'O=C1C(C)C(CC)CC1' }, name: { smiles: 'O=C1C(C)C(CC)CC1' }, explain: 'C=O is C1 of the ring; methyl on C2, ethyl on C3 → **3-ethyl-2-methylcyclopentanone**.' },
    { id: 'l08-q07', skill: 'l08.naming', type: 'mc', prompt: 'The common name of $CH_3COCH_2CH_3$ is…', choices: ['ethyl methyl ketone', 'methyl ethyl ether', 'butanal', 'propyl ketone'], answer: 0, explain: 'Both alkyl groups alphabetically + ketone → **ethyl methyl ketone** (MEK).' },
    { id: 'l08-q08', skill: 'l08.properties', type: 'order', prompt: 'Rank these by boiling point (lowest → highest).', items: ['1-butanol', 'pentane', 'butanal'], answer: [1, 2, 0], explain: 'Alkane (36 °C) < aldehyde (76 °C) < alcohol (118 °C).' },
    { id: 'l08-q09', skill: 'l08.properties', type: 'mc', prompt: 'Why do aldehydes and ketones boil **lower** than alcohols of similar size?', choices: ['They have no O–H, so no hydrogen bonding between molecules', 'They are nonpolar', 'They are heavier', 'They contain C=C'], answer: 0, explain: 'No O–H → **no H-bonding** between molecules (they are still polar).' },
    { id: 'l08-q10', skill: 'l08.properties', type: 'tf', prompt: 'True or false: 2-octanone (8 C) is soluble in water.', answer: false, explain: '**False.** Aldehydes/ketones with 7+ carbons are insoluble.' },
    { id: 'l08-q11', skill: 'l08.reactions', type: 'mc', prompt: 'Why can\'t ketones be oxidized?', choices: ['The carbonyl carbon has no C–H bond', 'They have no oxygen', 'They are too stable to react at all', 'They are already acids'], answer: 0, explain: 'Oxidation turns a C–H into C–O; a ketone\'s carbonyl carbon has **no H**.' },
    { id: 'l08-q12', skill: 'l08.reactions', type: 'match', prompt: 'Match each reaction to its product.', left: ['aldehyde + [O]', 'ketone + [O]', 'aldehyde + H₂, Pd', 'ketone + H₂, Pd'], right: ['carboxylic acid', 'no reaction', '1° alcohol', '2° alcohol'], answer: [0, 1, 2, 3], explain: 'Aldehyde oxidizes to an acid; ketones don\'t oxidize; reduction gives 1° (from aldehyde) or 2° (from ketone) alcohols.' },
    { id: 'l08-q13', skill: 'l08.reactions', type: 'mc', prompt: 'In the body, carbonyl compounds are reduced by…', choices: ['NADH (becoming NAD⁺)', 'H₂ and Pd', 'K₂Cr₂O₇', 'H₂SO₄'], answer: 0, explain: '**NADH** is the biological reducing agent; it is oxidized to NAD⁺.' },
    { id: 'l08-q14', skill: 'l08.health', type: 'mc', prompt: 'Formalin, used to preserve biological specimens, is a water solution of…', choices: ['formaldehyde', 'acetone', 'formic acid', 'methanol'], answer: 0, explain: 'Formalin = **37% formaldehyde** in water.' },
    { id: 'l08-q15', skill: 'l08.health', type: 'mc', prompt: 'Unusually high ketone levels in the blood of diabetic patients cause…', choices: ['diabetic ketoacidosis', 'scurvy', 'respiratory alkalosis', 'phocomelia'], answer: 0, explain: 'Ketones form when fatty acids break down; too many → **diabetic ketoacidosis**.' },
    { id: 'l08-q16', skill: 'l08.health', type: 'match', prompt: 'Match the flavor/scent to the compound.', left: ['cinnamon', 'vanilla', 'lemongrass', 'citronella candles'], right: ['cinnamaldehyde', 'vanillin', 'citral', 'citronellal'], answer: [0, 1, 2, 3], explain: 'These are all aldehydes with distinctive smells.' },
  ],
  cards: [
    { id: 'l08-k01', front: 'Aldehyde vs ketone', back: 'Aldehyde: ≥1 **H** on the C=O carbon (chain end). Ketone: **two C** on the C=O carbon.' },
    { id: 'l08-k02', front: 'Carbonyl geometry & polarity', back: 'Trigonal planar, **120°**. Polar: C is δ+, O is δ−.' },
    { id: 'l08-k03', front: 'Aldehyde naming', back: '-e → **-al**; CHO carbon is **C1** (no number): 2-methylhexanal.' },
    { id: 'l08-k04', front: 'Ketone naming', back: '-e → **-one**; lowest number to the C=O carbon: 2-butanone.' },
    { id: 'l08-k05', front: 'Common aldehyde names', back: '**formaldehyde** (HCHO), **acetaldehyde** (CH₃CHO), **benzaldehyde**.' },
    { id: 'l08-k06', front: 'Common ketone names', back: 'Alkyl groups alphabetically + **ketone**: ethyl methyl ketone. Acetone = 2-propanone.' },
    { id: 'l08-k07', front: 'bp ladder', back: 'alkane < **aldehyde/ketone** < alcohol (pentane 36, butanal 76, 2-butanone 80, 1-butanol 118 °C).' },
    { id: 'l08-k08', front: 'Aldehyde/ketone water solubility', back: '≤6 C: soluble. ≥7 C: insoluble.' },
    { id: 'l08-k09', front: 'Aldehyde + [O]', back: '→ **carboxylic acid** (C–H becomes C–OH).' },
    { id: 'l08-k10', front: 'Ketone + [O]', back: '**No reaction** (no C–H on the carbonyl carbon).' },
    { id: 'l08-k11', front: 'Reduction (definition)', back: '**Fewer C–O bonds** or **more C–H bonds**.' },
    { id: 'l08-k12', front: 'Aldehyde + H₂, Pd', back: '→ **1° alcohol**' },
    { id: 'l08-k13', front: 'Ketone + H₂, Pd', back: '→ **2° alcohol**' },
    { id: 'l08-k14', front: 'Biological reducing agent', back: '**NADH** → becomes NAD⁺ (an oxidizing agent).' },
    { id: 'l08-k15', front: 'Formalin', back: '37% **formaldehyde** in water — preserves specimens.' },
    { id: 'l08-k16', front: 'Diabetic ketoacidosis', back: 'Too many **ketones** from fatty-acid breakdown in the blood.' },
  ],
  keyTerms: [
    { term: 'carbonyl group', def: 'A C=O double bond.' },
    { term: 'aldehyde', def: 'A compound with a CHO group (H on the carbonyl carbon).' },
    { term: 'ketone', def: 'A compound with a C=O bonded to two carbons.' },
    { term: 'reduction', def: 'Loss of C–O bonds or gain of C–H bonds.' },
    { term: 'NADH', def: 'A coenzyme that acts as a biological reducing agent.' },
    { term: 'formalin', def: 'A 37% aqueous solution of formaldehyde.' },
  ],
};
