// Lecture 9 — Acids & Bases (Smith Ch. 9.1–9.2, 9.4, 9.6, 9.10–9.11)
export default {
  id: 'l09',
  number: 9,
  title: 'Acids & Bases',
  subtitle: 'Brønsted–Lowry, Ka, pH & buffers',
  chapter: 'Ch. 9 (9.1–9.2, 9.4, 9.6, 9.10–9.11)',
  tested: false,
  summary: 'Proton donors and acceptors, conjugate pairs, Ka and acid strength, pH calculations (with the sig-fig rule), buffers, and how your blood stays at pH 7.4.',
  skills: [
    { id: 'l09.bronsted', title: 'Acid & base definitions', desc: 'Arrhenius vs Brønsted–Lowry; spotting the acid and base in a reaction.' },
    { id: 'l09.conjugates', title: 'Conjugate acid–base pairs', desc: 'Add or remove one H⁺ (and adjust the charge).' },
    { id: 'l09.ka', title: 'Ka & acid strength', desc: 'Writing Ka; larger Ka = stronger acid.' },
    { id: 'l09.ph', title: 'pH calculations', desc: 'pH = −log[H₃O⁺], and back; acidic/basic/neutral.' },
    { id: 'l09.buffers', title: 'Buffers', desc: 'Weak acid + conjugate base; how buffers resist pH change.' },
    { id: 'l09.blood', title: 'Blood pH', desc: 'H₂CO₃/HCO₃⁻, acidosis and alkalosis.' },
  ],
  sections: [
    {
      id: 'definitions',
      title: 'What are acids and bases?',
      minutes: 7,
      blocks: [
        {
          t: 'compare', items: [
            { title: 'Arrhenius (earliest)', text: 'Acid: contains H and forms **H⁺** in water ($HCl → H^+^ + Cl^−^$). Base: contains OH and forms **OH⁻** in water ($NaOH → Na^+^ + OH^−^$).' },
            { title: 'Brønsted–Lowry (used in this class)', text: 'Acid = **proton (H⁺) donor**. Base = **proton (H⁺) acceptor**.' },
          ],
        },
        { t: 'p', text: 'The Arrhenius definition is limited: a free H⁺ doesn\'t really exist in water. It bonds to water to make the **hydronium ion, $H_3O^+^$**.' },
        { t: 'callout', kind: 'key', title: 'Example', text: '$HCl + H_2O → H_3O^+^ + Cl^−^$\nHCl **donates** a proton → Brønsted–Lowry **acid**. $H_2O$ **accepts** it → Brønsted–Lowry **base**.' },
        { t: 'list', items: ['A Brønsted–Lowry **acid must contain an H** (HCl, HBr, $H_2SO_4$, $HNO_3$, and the acidic H of acetic acid $CH_3COOH$).', 'A Brønsted–Lowry **base must have a lone pair** to form a new bond to H⁺ (e.g. $NH_3$, $OH^−^$, $H_2O$).'] },
        { t: 'callout', kind: 'memory', title: 'Memory trick', text: 'Ac**id** = **d**onates. **B**ase = **b**onds to (accepts) the proton.' },
      ],
    },
    {
      id: 'conjugates',
      title: 'Conjugate acid–base pairs',
      minutes: 8,
      blocks: [
        { t: 'p', text: 'When an acid HA reacts with a base B, the proton moves from HA to B:' },
        { t: 'callout', kind: 'key', title: 'HA + B → A⁻ + HB⁺', text: '- **A⁻** (the acid after losing H⁺) is the **conjugate base**.\n- **HB⁺** (the base after gaining H⁺) is the **conjugate acid**.' },
        {
          t: 'example', title: 'Identify all four', prompt: '$HBr + H_2O → Br^−^ + H_3O^+^$',
          steps: ['HBr loses H⁺ → **acid**; Br⁻ is its **conjugate base**.', '$H_2O$ gains H⁺ → **base**; $H_3O^+^$ is its **conjugate acid**.', 'Pairs: HBr/Br⁻ and $H_3O^+^$/$H_2O$.'],
          answer: 'acid HBr · base H₂O · conjugate base Br⁻ · conjugate acid H₃O⁺',
        },
        { t: 'callout', kind: 'tip', title: 'Charge bookkeeping', text: 'Gain an H⁺ → charge goes **up by 1** ($H_2O$ → $H_3O^+^$). Lose an H⁺ → charge goes **down by 1** (HBr → Br⁻). The net charge must be the same on both sides of the equation.' },
        {
          t: 'check', q: {
            id: 'l09-c-conj', skill: 'l09.conjugates', type: 'mc', prompt: 'What is the conjugate base of $HSO_4^−^$?',
            choices: ['SO₄²⁻', 'H₂SO₄', 'HSO₄', 'H₃O⁺'], answer: 0,
            explain: 'Remove one H⁺ and lower the charge by 1: HSO₄⁻ → **SO₄²⁻**.',
          },
        },
      ],
    },
    {
      id: 'ka',
      title: 'Equilibrium and Ka',
      minutes: 8,
      blocks: [
        { t: 'p', text: 'When an acid HA dissolves in water, it sets up an equilibrium: $HA + H_2O ⇌ H_3O^+^ + A^−^$. The **acid dissociation constant** is:' },
        { t: 'callout', kind: 'key', title: 'Ka = [H₃O⁺][A⁻] / [HA]', text: '- It\'s the ratio of **products to reactants** at equilibrium ([X] = concentration).\n- **Water does not appear** in the expression.' },
        {
          t: 'example', title: 'Write Ka', prompt: '$CH_3COOH + H_2O ⇌ H_3O^+^ + CH_3COO^−^$',
          steps: ['Products on top: $[H_3O^+^][CH_3COO^−^]$.', 'Reactant on the bottom (not water): $[CH_3COOH]$.'],
          answer: 'Ka = [H₃O⁺][CH₃COO⁻] / [CH₃COOH]',
        },
        { t: 'callout', kind: 'key', title: 'Strength', text: '**The stronger the acid, the larger its Ka.** Equilibrium favors formation of the **weaker acid** (the one with the smaller Ka).' },
        {
          t: 'table', head: ['Acid', 'Ka'],
          rows: [['HSO₄⁻', '1.2 × 10^−2^'], ['H₃PO₄', '7.5 × 10^−3^'], ['HF', '7.2 × 10^−4^'], ['CH₃COOH (acetic acid)', '1.8 × 10^−5^'], ['H₂CO₃ (carbonic acid)', '4.3 × 10^−7^'], ['NH₄⁺', '5.6 × 10^−10^'], ['HCN', '4.9 × 10^−10^']],
          caption: 'Some weak acids, strongest at the top.',
        },
        { t: 'callout', kind: 'tip', title: 'Comparing numbers like 1.5 × 10⁻⁴', text: 'Look at the **exponent first**: 10^−2^ > 10^−4^ > 10^−10^. Only compare the front numbers if the exponents match. (0.12 > 0.021 > 0.0035 > 1.5 × 10^−4^ > 0.000034.)' },
      ],
    },
    {
      id: 'ph',
      title: 'The pH scale',
      minutes: 12,
      blocks: [
        { t: 'callout', kind: 'key', title: 'pH = −log[H₃O⁺]', text: 'The **lower** the pH, the **higher** the $[H_3O^+^]$.\n- Acidic: pH **< 7**, $[H_3O^+^]$ > 1 × 10^−7^ M\n- Neutral: pH **= 7**, $[H_3O^+^]$ = 1 × 10^−7^ M\n- Basic: pH **> 7**, $[H_3O^+^]$ < 1 × 10^−7^ M' },
        { t: 'table', head: ['Everyday item', 'approx. pH'], rows: [['lemon juice', '2'], ['tomatoes', '4'], ['milk', '6.5'], ['pure water', '7'], ['milk of magnesia', '10.5'], ['household ammonia', '11'], ['bleach', '12.5']] },
        { t: 'h', text: 'Calculating pH with a calculator' },
        {
          t: 'example', title: 'Concentration → pH', prompt: '$[H_3O^+^]$ = 1.2 × 10^−5^ M. What is the pH?',
          steps: ['pH = −log(1.2 × 10^−5^)', 'log(1.2 × 10^−5^) = −4.92, so pH = −(−4.92) = **4.92**.', '**Sig figs:** 1.2 has **2 digits** → the pH gets **2 decimal places**.', 'pH < 7 → **acidic**.'],
          answer: 'pH = 4.92 (acidic)',
        },
        {
          t: 'example', title: 'Another one', prompt: '$[H_3O^+^]$ = 1.4 × 10^−10^ M. What is the pH?',
          steps: ['pH = −log(1.4 × 10^−10^) = 9.85', 'pH > 7 → **basic**.'],
          answer: 'pH = 9.85 (basic)',
        },
        {
          t: 'example', title: 'pH → concentration', prompt: 'The pH of a solution is 4.50. What is $[H_3O^+^]$?',
          steps: ['4.50 = −log[H₃O⁺] → log[H₃O⁺] = −4.50', '[H₃O⁺] = **antilog(−4.50)** = 10^−4.50^ (use the 10^x^ key)', '= 3.2 × 10^−5^ M (2 decimal places in pH → 2 sig figs).'],
          answer: '3.2 × 10⁻⁵ M (acidic, because > 1 × 10⁻⁷ M)',
        },
        { t: 'callout', kind: 'tip', title: 'Calculator keys', text: '**pH from concentration:** type 1.2, EE (or ×10^x^), −5, then **log**, then change the sign.\n**Concentration from pH:** press **10^x^** (often 2nd + log) and enter −pH.' },
        { t: 'link', text: 'Open the pH calculator in Tools →', href: '#/tools/ph' },
      ],
    },
    {
      id: 'buffers',
      title: 'Buffers',
      minutes: 8,
      blocks: [
        { t: 'p', text: 'A **buffer** is a solution whose pH changes very little when acid or base is added. Most buffers contain roughly **equal amounts of a weak acid and the salt of its conjugate base**.' },
        { t: 'callout', kind: 'key', title: 'How a buffer works (acetic acid / acetate)', text: '- Add **base** (OH⁻): it reacts with the **weak acid** ($CH_3COOH + OH^−^ → CH_3COO^−^ + H_2O$).\n- Add **acid** (H₃O⁺): it reacts with the **conjugate base** ($CH_3COO^−^ + H_3O^+^ → CH_3COOH + H_2O$).\nEither way, the added acid or base is "used up," so the pH barely moves.' },
        { t: 'table', head: ['Buffer', 'Weak acid', 'Conjugate base', 'Ka'], rows: [['acetic acid/acetate', 'CH₃COOH', 'CH₃COO⁻', '1.8 × 10^−5^'], ['bicarbonate/carbonate', 'HCO₃⁻', 'CO₃²⁻', '5.6 × 10^−11^'], ['dihydrogen phosphate/hydrogen phosphate', 'H₂PO₄⁻', 'HPO₄²⁻', '6.2 × 10^−8^']] },
        { t: 'p', text: 'The buffer\'s pH is set by its Ka: rearranging the Ka expression gives $[H_3O^+^]$ = Ka × [HA]/[A⁻]. With equal amounts of HA and A⁻, $[H_3O^+^]$ = Ka.' },
        { t: 'callout', kind: 'warn', title: 'Not a buffer', text: 'A **strong** acid and its salt (HCl + NaCl) can\'t buffer — Cl⁻ is too weak a base to soak up added acid.' },
      ],
    },
    {
      id: 'blood',
      title: 'Focus on the human body: blood buffers',
      minutes: 6,
      blocks: [
        { t: 'p', text: 'Normal blood pH is **7.35–7.45**. The main buffer is **carbonic acid / bicarbonate ($H_2CO_3$ / $HCO_3^−^$)**, which is tied to the CO₂ your cells constantly produce:' },
        { t: 'callout', kind: 'key', title: 'CO₂ + H₂O ⇌ H₂CO₃ ⇌ H₃O⁺ + HCO₃⁻', text: 'More CO₂ pushes this to the right → more H₃O⁺ → **lower pH**. Less CO₂ pulls it left → **higher pH**.' },
        {
          t: 'compare', items: [
            { title: 'Respiratory acidosis', text: 'The body **can\'t get rid of enough CO₂** (lung disease or failure) → CO₂ builds up → **pH drops**.' },
            { title: 'Respiratory alkalosis', text: '**Hyperventilating** blows off too much CO₂ → **pH rises**.' },
          ],
        },
      ],
    },
  ],
  questions: [
    { id: 'l09-q01', skill: 'l09.bronsted', type: 'mc', prompt: 'A Brønsted–Lowry acid is a…', choices: ['proton (H⁺) donor', 'proton acceptor', 'hydroxide donor', 'electron pair donor'], answer: 0, explain: 'Acid **donates** H⁺; base **accepts** H⁺.' },
    { id: 'l09-q02', skill: 'l09.bronsted', type: 'mc', prompt: 'What must every Brønsted–Lowry base have?', choices: ['a lone pair of electrons', 'an OH group', 'a positive charge', 'a hydrogen atom'], answer: 0, explain: 'It needs a **lone pair** to form the new bond to H⁺.' },
    { id: 'l09-q03', skill: 'l09.bronsted', type: 'mc', prompt: 'Why is "H⁺ in water" really written as $H_3O^+^$?', choices: ['A free proton bonds to a water molecule', 'H⁺ is too heavy', 'Water is an acid', 'It\'s just a convention with no meaning'], answer: 0, explain: 'H⁺ doesn\'t exist freely; it bonds to H₂O to form the **hydronium ion**.' },
    { id: 'l09-q04', skill: 'l09.bronsted', type: 'mc', prompt: 'In $NH_3 + H_2O → NH_4^+^ + OH^−^$, which species is the **acid**?', choices: ['H₂O', 'NH₃', 'NH₄⁺', 'OH⁻'], answer: 0, shuffle: false, explain: '$H_2O$ gives an H⁺ to NH₃ → **water is the acid** here (NH₃ is the base).' },
    { id: 'l09-q05', skill: 'l09.conjugates', type: 'mc', prompt: 'What is the conjugate acid of $NH_3$?', choices: ['NH₄⁺', 'NH₂⁻', 'H₃O⁺', 'OH⁻'], answer: 0, explain: 'Add one H⁺ and raise the charge by 1 → **NH₄⁺**.' },
    { id: 'l09-q06', skill: 'l09.conjugates', type: 'match', prompt: 'Match each acid with its conjugate base.', left: ['HCl', 'H₃O⁺', 'CH₃COOH', 'H₂CO₃'], right: ['Cl⁻', 'H₂O', 'CH₃COO⁻', 'HCO₃⁻'], answer: [0, 1, 2, 3], explain: 'Each conjugate base is the acid minus one H⁺.' },
    { id: 'l09-q07', skill: 'l09.ka', type: 'mc', prompt: 'Which acid is **strongest**?', choices: ['Ka = 0.12', 'Ka = 0.021', 'Ka = 0.0035', 'Ka = 1.5 × 10⁻⁴'], answer: 0, shuffle: false, explain: 'Largest Ka → strongest acid: **0.12**.' },
    { id: 'l09-q08', skill: 'l09.ka', type: 'tf', prompt: 'True or false: water appears in the denominator of a Ka expression.', answer: false, explain: '**False.** Ka = [H₃O⁺][A⁻]/[HA] — water is left out.' },
    { id: 'l09-q09', skill: 'l09.ka', type: 'mc', prompt: 'At equilibrium, an acid–base reaction favors formation of…', choices: ['the weaker acid', 'the stronger acid', 'water only', 'equal amounts always'], answer: 0, explain: 'Equilibrium favors the **weaker acid** (smaller Ka).' },
    { id: 'l09-q10', skill: 'l09.ph', type: 'num', prompt: '$[H_3O^+^]$ = 1.4 × 10^−6^ M. What is the pH?', answer: 5.85, tol: 0.011, decimals: 2, explain: 'pH = −log(1.4 × 10^−6^) = **5.85** (acidic).' },
    { id: 'l09-q11', skill: 'l09.ph', type: 'num', prompt: 'The pH is 9.50. What is $[H_3O^+^]$ in M?', answer: 3.2e-10, rel: 0.04, answerText: '3.2 × 10⁻¹⁰ M', explain: '[H₃O⁺] = 10^−9.50^ = **3.2 × 10^−10^ M** (basic).' },
    { id: 'l09-q12', skill: 'l09.ph', type: 'mc', prompt: 'A solution has $[H_3O^+^]$ = 1 × 10^−9^ M. It is…', choices: ['basic', 'acidic', 'neutral'], answer: 0, shuffle: false, explain: '1 × 10^−9^ is **less** than 1 × 10^−7^ → pH 9 → **basic**.' },
    { id: 'l09-q13', skill: 'l09.ph', type: 'mc', prompt: 'How many decimal places should you report for the pH of a solution with $[H_3O^+^]$ = 2.5 × 10^−4^ M?', choices: ['2', '1', '3', '4'], answer: 0, shuffle: false, explain: '2.5 has **2 significant digits** → **2 decimal places** in the pH (3.60).' },
    { id: 'l09-q14', skill: 'l09.buffers', type: 'mc', prompt: 'In an acetic acid/acetate buffer, added OH⁻ reacts with…', choices: ['CH₃COOH (the weak acid)', 'CH₃COO⁻ (the conjugate base)', 'Na⁺', 'nothing'], answer: 0, explain: 'Added **base** is neutralized by the **weak acid**.' },
    { id: 'l09-q15', skill: 'l09.buffers', type: 'mc', prompt: 'In a buffer, added $H_3O^+^$ reacts with…', choices: ['the conjugate base', 'the weak acid', 'water', 'the metal ion'], answer: 0, explain: 'Added **acid** is neutralized by the **conjugate base**.' },
    { id: 'l09-q16', skill: 'l09.blood', type: 'mc', prompt: 'Lung failure that prevents CO₂ from being exhaled causes…', choices: ['respiratory acidosis (pH drops)', 'respiratory alkalosis (pH rises)', 'no change', 'ketoacidosis'], answer: 0, explain: 'CO₂ builds up → more H₂CO₃ → more H₃O⁺ → **acidosis**.' },
    { id: 'l09-q17', skill: 'l09.blood', type: 'mc', prompt: 'Normal blood pH is…', choices: ['7.35–7.45', '6.35–6.45', '7.00 exactly', '8.35–8.45'], answer: 0, explain: '**7.35–7.45**, kept steady by the H₂CO₃/HCO₃⁻ buffer.' },
  ],
  cards: [
    { id: 'l09-k01', front: 'Arrhenius acid / base', back: 'Acid forms **H⁺** in water; base forms **OH⁻** in water.' },
    { id: 'l09-k02', front: 'Brønsted–Lowry acid / base', back: 'Acid = **H⁺ donor**; base = **H⁺ acceptor** (needs a lone pair).' },
    { id: 'l09-k03', front: 'Hydronium ion', back: '$H_3O^+^$ — what H⁺ actually becomes in water.' },
    { id: 'l09-k04', front: 'Conjugate base', back: 'What\'s left after the acid **loses H⁺** (charge − 1): HBr → Br⁻.' },
    { id: 'l09-k05', front: 'Conjugate acid', back: 'What forms when the base **gains H⁺** (charge + 1): H₂O → H₃O⁺.' },
    { id: 'l09-k06', front: 'Ka expression', back: 'Ka = [H₃O⁺][A⁻] / [HA] — products over reactants, **no water**.' },
    { id: 'l09-k07', front: 'Ka and acid strength', back: '**Larger Ka = stronger acid.** Equilibrium favors the weaker acid.' },
    { id: 'l09-k08', front: 'pH formula', back: 'pH = −log[H₃O⁺]; [H₃O⁺] = 10^−pH^' },
    { id: 'l09-k09', front: 'Acidic / neutral / basic', back: 'pH < 7 / = 7 / > 7. [H₃O⁺] > / = / < 1 × 10^−7^ M.' },
    { id: 'l09-k10', front: 'pH sig-fig rule', back: 'Digits in the concentration = **decimal places** in the pH (1.2 × 10⁻⁵ → 4.92).' },
    { id: 'l09-k11', front: 'Buffer', back: 'Weak acid + salt of its conjugate base; **resists pH change**.' },
    { id: 'l09-k12', front: 'How a buffer handles added base / acid', back: 'Base reacts with the **weak acid**; acid reacts with the **conjugate base**.' },
    { id: 'l09-k13', front: 'Main blood buffer', back: '**H₂CO₃ / HCO₃⁻**; blood pH 7.35–7.45.' },
    { id: 'l09-k14', front: 'Respiratory acidosis', back: 'Can\'t exhale enough CO₂ (lung disease) → **pH falls**.' },
    { id: 'l09-k15', front: 'Respiratory alkalosis', back: '**Hyperventilation** → too little CO₂ → **pH rises**.' },
  ],
  keyTerms: [
    { term: 'Brønsted–Lowry acid', def: 'A proton (H⁺) donor.' },
    { term: 'Brønsted–Lowry base', def: 'A proton (H⁺) acceptor.' },
    { term: 'hydronium ion', def: 'H₃O⁺, formed when H⁺ bonds to water.' },
    { term: 'conjugate base', def: 'The species formed when an acid loses a proton.' },
    { term: 'conjugate acid', def: 'The species formed when a base gains a proton.' },
    { term: 'acid dissociation constant (Ka)', def: 'Ka = [H₃O⁺][A⁻]/[HA]; larger Ka = stronger acid.' },
    { term: 'pH', def: '−log[H₃O⁺]; below 7 acidic, above 7 basic.' },
    { term: 'buffer', def: 'A solution that resists changes in pH (weak acid + conjugate base).' },
  ],
};
