// Lecture 10 — Carboxylic Acids (Smith Ch. 17.1, 17.2A, 17.3, 17.4, 17.6, 17.7)
export default {
  id: 'l10',
  number: 10,
  title: 'Carboxylic Acids',
  subtitle: 'Naming, properties, acidity, salts & soap',
  chapter: 'Ch. 17.1–17.7',
  tested: false,
  summary: 'The COOH group: naming with -oic acid, the highest boiling points in the course, reaction with bases to make water-soluble salts, how soap works, and how aspirin travels through your body.',
  skills: [
    { id: 'l10.structure', title: 'Structure & α/β carbons', desc: 'The carboxyl group; α and β carbons.' },
    { id: 'l10.naming', title: 'Naming carboxylic acids', desc: '-oic acid, COOH carbon = C1; common names.' },
    { id: 'l10.properties', title: 'Physical properties', desc: 'Higher boiling points than alcohols; odors.' },
    { id: 'l10.salts', title: 'Acidity & carboxylate salts', desc: 'Weak acids; RCOOH + NaOH → RCOO⁻Na⁺ + H₂O; naming salts.' },
    { id: 'l10.soap', title: 'Soap', desc: 'Polar head, nonpolar tail, micelles.' },
    { id: 'l10.health', title: 'Acids in health & medicine', desc: 'NSAIDs, prostaglandins, α-hydroxy acids, aspirin absorption.' },
  ],
  sections: [
    {
      id: 'structure',
      title: 'Structure and bonding',
      minutes: 5,
      blocks: [
        { t: 'p', text: '**Carboxylic acids** contain a **carboxyl group, COOH**: a C=O with an OH on the same carbon. They are written **RCOOH** or **RCO₂H**.' },
        { t: 'mols', items: [{ smiles: 'CC(=O)O', caption: 'acetic acid, CH₃COOH' }, { smiles: 'CCCC(=O)O', caption: 'butanoic acid' }] },
        { t: 'list', items: ['The carbonyl carbon is **trigonal planar**: bond angles **120°**.', 'The C=O is **polar**: O is δ−, the carbonyl C is δ+.'] },
        { t: 'h', text: 'α and β carbons' },
        { t: 'p', text: 'The carbon **next to** the COOH carbon is the **α (alpha) carbon**; the next one out is the **β (beta) carbon**.' },
        { t: 'mol', smiles: 'CCCC(=O)O', caption: 'In butanoic acid: C2 is α, C3 is β.', numbers: 'auto' },
      ],
    },
    {
      id: 'naming',
      title: 'Naming carboxylic acids',
      minutes: 8,
      blocks: [
        { t: 'steps', title: 'HOW TO name a carboxylic acid', items: ['Find the longest chain **containing the COOH** carbon.', 'Number the chain so the **COOH carbon is C1** (the "1" is not written).', 'Change the -e of the alkane to **-oic acid**.', 'Apply all the other naming rules.'] },
        {
          t: 'example', title: 'Sample Problem 17.1 style', prompt: 'Name this carboxylic acid.',
          mol: { smiles: 'CCC(C)CC(C)C(=O)O', numbers: 'auto', name: '2,4-dimethylhexanoic acid' },
          steps: ['Longest chain including the COOH carbon: 6 C → hexan**oic acid**.', 'COOH carbon = C1; methyls on C2 and C4.'],
          answer: '**2,4-dimethylhexanoic acid**',
        },
        { t: 'mols', items: [{ smiles: 'CCC(C)C(=O)O', caption: '2-methylbutanoic acid', numbers: 'auto', name: '2-methylbutanoic acid' }, { smiles: 'CCCCC(CC)C(=O)O', caption: '2-ethylhexanoic acid', numbers: 'auto', name: '2-ethylhexanoic acid' }] },
        { t: 'h', text: 'Common names you need' },
        {
          t: 'table', head: ['Common name', 'Formula', 'Where it shows up'],
          rows: [['**formic acid**', '$HCOOH$', 'the sting of **fire ants**'], ['**acetic acid**', '$CH_3COOH$', 'sour taste of **vinegar**'], ['**benzoic acid**', '$C_6H_5COOH$', '**food preservative**']],
        },
        { t: 'mols', items: [{ smiles: 'OC=O', caption: 'formic acid' }, { smiles: 'CC(=O)O', caption: 'acetic acid' }, { smiles: 'OC(=O)c1ccccc1', caption: 'benzoic acid' }] },
        {
          t: 'check', q: {
            id: 'l10-c-name', skill: 'l10.naming', type: 'name', prompt: 'Name this acid.',
            figure: { smiles: 'CCC(C)C(=O)O' }, name: { smiles: 'CCC(C)C(=O)O' },
            explain: '4-carbon chain counting the COOH carbon (C1); methyl on C2 → **2-methylbutanoic acid**.',
          },
        },
      ],
    },
    {
      id: 'properties',
      title: 'Physical properties & interesting acids',
      minutes: 6,
      blocks: [
        { t: 'callout', kind: 'key', title: 'Highest on the ladder', text: 'Carboxylic acids have **higher boiling points than alcohols** of similar size, because they can form **more hydrogen bonds** (pairs of acid molecules H-bond to each other through both the C=O and the O–H).' },
        { t: 'callout', kind: 'tip', title: 'The whole boiling-point ladder (similar size)', text: 'alkane < ether < aldehyde/ketone < alcohol < **carboxylic acid**' },
        { t: 'table', head: ['Compound', 'bp'], rows: [['1-propanol', '97 °C'], ['acetic acid', '118 °C']], caption: 'Same molecular weight (60 g/mol)' },
        { t: 'list', items: ['Small carboxylic acids have **foul or biting odors**.', '**Formic acid** (HCO₂H): the sting of some ants.', '**Acetic acid** (CH₃CO₂H): vinegar — forms when wine "goes bad" by air oxidation of ethanol.', '**Hexanoic acid** (CH₃(CH₂)₄COOH): the smell of dirty socks and locker rooms.'] },
      ],
    },
    {
      id: 'health',
      title: 'Focus on health: skin care & pain relievers',
      minutes: 5,
      blocks: [
        { t: 'p', text: '**α-Hydroxy acids** (an OH on the α carbon) are in skin care products that claim to smooth fine lines. They remove the outer layer of older skin cells, revealing newer cells underneath.' },
        { t: 'mols', items: [{ smiles: 'OCC(=O)O', caption: 'glycolic acid' }, { smiles: 'CC(O)C(=O)O', caption: 'lactic acid' }] },
        { t: 'p', text: 'Three common pain relievers that are also anti-inflammatory (NSAIDs) contain a carboxyl group. They work by **blocking the synthesis of prostaglandins**, compounds responsible for pain and inflammation.' },
        { t: 'mols', items: [{ smiles: 'CC(=O)Oc1ccccc1C(=O)O', caption: 'aspirin' }, { smiles: 'CC(C)Cc1ccc(cc1)C(C)C(=O)O', caption: 'ibuprofen' }, { smiles: 'COc1ccc2cc(ccc2c1)C(C)C(=O)O', caption: 'naproxen' }] },
      ],
    },
    {
      id: 'acidity',
      title: 'Acidity & carboxylate salts',
      minutes: 9,
      blocks: [
        { t: 'p', text: 'Carboxylic acids are **proton (H⁺) donors** — but they are **weak acids** compared with inorganic acids like HCl or H₂SO₄. Only a **small percentage** ionizes in water.' },
        { t: 'callout', kind: 'key', title: 'Reaction with bases', text: '**RCOOH + NaOH → RCOO⁻ Na⁺ + H₂O**\nThe acid donates its proton to OH⁻ (which accepts it), making water and a **carboxylate salt**.' },
        { t: 'rxn', from: 'CCCCCCCC(=O)O', reagent: 'NaOH', to: 'CCCCCCCC(=O)[O-].[Na+]', caption: 'octanoic acid (water insoluble) → sodium octanoate (water soluble) + H₂O' },
        { t: 'p', text: 'Carboxylate salts are **ionic solids** and are **water soluble**, so this reaction turns a water-insoluble acid into a water-soluble salt.' },
        { t: 'h', text: 'Naming carboxylate salts' },
        { t: 'steps', items: ['Name the **metal** first (sodium, potassium).', 'Take the acid name and change **-ic acid** to **-ate**.'] },
        { t: 'mols', items: [{ smiles: 'CC(=O)[O-].[Na+]', caption: 'sodium acetate', name: 'sodium acetate' }, { smiles: 'CCC(=O)[O-].[K+]', caption: 'potassium propanoate', name: 'potassium propanoate' }] },
        {
          t: 'check', q: {
            id: 'l10-c-salt', skill: 'l10.salts', type: 'name', prompt: 'Name the organic product: butanoic acid + NaOH →',
            figure: { rxn: { from: 'CCCC(=O)O', reagent: 'NaOH' } }, name: { smiles: 'CCCC(=O)[O-].[Na+]' },
            explain: 'Sodium + butan**oic acid** → butan**oate** → **sodium butanoate** (plus water).',
          },
        },
      ],
    },
    {
      id: 'soap',
      title: 'How does soap clean away dirt?',
      minutes: 6,
      blocks: [
        { t: 'p', text: 'People have used soap for about 2000 years. **Soaps are salts of carboxylic acids with long carbon chains.** A soap molecule has two parts:' },
        {
          t: 'compare', items: [
            { title: 'Polar head (ionic end)', text: 'The COO⁻ Na⁺ end — attracted to **water**.' },
            { title: 'Nonpolar tail', text: 'The long chain of C–C and C–H bonds — attracted to **grease and oil**.' },
          ],
        },
        { t: 'mol', smiles: 'CCCCCCCCCCCCCCCCCC(=O)[O-].[Na+]', caption: 'sodium stearate, a soap: long nonpolar tail + ionic head' },
        { t: 'p', text: 'In water, soap forms **micelles**: spherical droplets with the **ionic heads on the outside** (touching water) and the **nonpolar tails packed inside**. Grease and oil dissolve in the nonpolar interior, and the whole micelle washes away with water.' },
      ],
    },
    {
      id: 'aspirin',
      title: 'Focus on health: how aspirin gets absorbed',
      minutes: 4,
      blocks: [
        { t: 'p', text: 'Aspirin is a carboxylic acid. Whether it\'s neutral or ionic depends on the surroundings:' },
        {
          t: 'compare', items: [
            { title: 'Stomach (acidic)', text: 'Aspirin stays in its **neutral** form (RCOOH).' },
            { title: 'Intestines (basic)', text: 'Aspirin loses H⁺ and exists as the **ionic** carboxylate (RCOO⁻).' },
          ],
        },
        { t: 'mols', items: [{ smiles: 'CC(=O)Oc1ccccc1C(=O)O', caption: 'neutral form (stomach)' }, { smiles: 'CC(=O)Oc1ccccc1C(=O)[O-]', caption: 'ionic form (intestines)' }] },
        { t: 'callout', kind: 'key', title: 'Why it matters', text: 'Passage through the **cell membrane** (nonpolar) happens in the **neutral** form.' },
      ],
    },
  ],
  questions: [
    { id: 'l10-q01', skill: 'l10.structure', type: 'mc', prompt: 'The carboxyl group is…', choices: ['–COOH', '–CHO', '–COC–', '–OH'], answer: 0, explain: '**–COOH** (C=O with OH on the same carbon).' },
    { id: 'l10-q02', skill: 'l10.structure', type: 'mc', prompt: 'The α carbon of a carboxylic acid is…', choices: ['the carbon bonded to the COOH carbon', 'the COOH carbon itself', 'the last carbon in the chain', 'any carbon with an OH'], answer: 0, explain: 'α = the carbon **next to** the COOH carbon; β is the next one.' },
    { id: 'l10-q03', skill: 'l10.naming', type: 'mc', prompt: 'What suffix is used for carboxylic acids?', choices: ['-oic acid', '-al', '-ol', '-one'], answer: 0, explain: 'Change -e to **-oic acid**: butane → butanoic acid.' },
    { id: 'l10-q04', skill: 'l10.naming', type: 'name', prompt: 'Name this acid.', figure: { smiles: 'CCCCC(CC)C(=O)O' }, name: { smiles: 'CCCCC(CC)C(=O)O' }, explain: 'Six-carbon chain with the COOH as C1; ethyl on C2 → **2-ethylhexanoic acid**.' },
    { id: 'l10-q05', skill: 'l10.naming', type: 'match', prompt: 'Match the common name to where it\'s found.', left: ['formic acid', 'acetic acid', 'benzoic acid', 'hexanoic acid'], right: ['fire ant stings', 'vinegar', 'food preservative', 'dirty socks smell'], answer: [0, 1, 2, 3], explain: 'Formic → ants; acetic → vinegar; benzoic → preservative; hexanoic → locker-room smell.' },
    { id: 'l10-q06', skill: 'l10.properties', type: 'mc', prompt: 'Why does acetic acid boil higher than 1-propanol (same MW)?', choices: ['Acids form more hydrogen bonds', 'Acids are nonpolar', 'Acetic acid is ionic', 'Propanol has no oxygen'], answer: 0, explain: 'Carboxylic acids have **more H-bonding** (C=O and O–H both involved).' },
    { id: 'l10-q07', skill: 'l10.properties', type: 'order', prompt: 'Rank by boiling point (lowest → highest), similar size.', items: ['propanoic acid', 'butane', '1-propanol', 'propanal'], answer: [1, 3, 2, 0], explain: 'butane (−0.5) < propanal (48) < 1-propanol (97) < propanoic acid (141 °C).' },
    { id: 'l10-q08', skill: 'l10.salts', type: 'mc', prompt: 'Compared with HCl, carboxylic acids are…', choices: ['weak acids (only slightly ionized)', 'strong acids', 'bases', 'neutral'], answer: 0, explain: 'Only a **small percentage** of a carboxylic acid ionizes in water.' },
    { id: 'l10-q09', skill: 'l10.salts', type: 'mc', prompt: 'RCOOH + NaOH → ?', choices: ['RCOO⁻Na⁺ + H₂O', 'RCOONa + H₂', 'RCH₂OH + NaO', 'no reaction'], answer: 0, explain: 'Acid + base → **carboxylate salt + water**.' },
    { id: 'l10-q10', skill: 'l10.salts', type: 'tf', prompt: 'True or false: converting octanoic acid into sodium octanoate makes it water soluble.', answer: true, explain: '**True.** The salt is ionic, so it dissolves in water.' },
    { id: 'l10-q11', skill: 'l10.salts', type: 'name', prompt: 'Name this salt.', figure: { smiles: 'CCC(=O)[O-].[K+]' }, name: { smiles: 'CCC(=O)[O-].[K+]' }, explain: 'Potassium + propanoic acid → **potassium propanoate**.' },
    { id: 'l10-q12', skill: 'l10.soap', type: 'mc', prompt: 'A soap molecule is best described as…', choices: ['a long nonpolar tail with an ionic head', 'a short polar molecule', 'a long nonpolar molecule with no charge', 'a strong acid'], answer: 0, explain: 'Soap = salt of a long-chain carboxylic acid: **ionic head + nonpolar tail**.' },
    { id: 'l10-q13', skill: 'l10.soap', type: 'mc', prompt: 'In a micelle, where does the grease end up?', choices: ['in the nonpolar interior, among the tails', 'on the outer surface', 'dissolved in the water between micelles', 'bonded to the Na⁺ ions'], answer: 0, explain: 'Nonpolar grease dissolves among the **nonpolar tails inside**; ionic heads face the water.' },
    { id: 'l10-q14', skill: 'l10.health', type: 'mc', prompt: 'NSAIDs like aspirin, ibuprofen and naproxen relieve pain by…', choices: ['blocking prostaglandin synthesis', 'killing bacteria', 'reducing blood pH', 'forming disulfide bonds'], answer: 0, explain: 'They block the synthesis of **prostaglandins**, which cause pain and inflammation.' },
    { id: 'l10-q15', skill: 'l10.health', type: 'mc', prompt: 'In the stomach, aspirin exists mainly as…', choices: ['the neutral acid (RCOOH)', 'the carboxylate ion (RCOO⁻)', 'a salt with Na⁺', 'an ester only'], answer: 0, explain: 'The stomach is acidic, so aspirin stays **neutral**; in the basic intestines it becomes **ionic**.' },
    { id: 'l10-q16', skill: 'l10.health', type: 'mc', prompt: 'α-Hydroxy acids in skin care work by…', choices: ['removing the outer layer of old skin cells', 'blocking prostaglandins', 'adding moisture from fat', 'killing bacteria'], answer: 0, explain: 'They **exfoliate** the outer layer, revealing newer cells.' },
  ],
  cards: [
    { id: 'l10-k01', front: 'Carboxyl group', back: '**–COOH** (–CO₂H): C=O with OH on the same carbon.' },
    { id: 'l10-k02', front: 'α and β carbons', back: 'α = next to the COOH carbon; β = the one after that.' },
    { id: 'l10-k03', front: 'Naming carboxylic acids', back: 'Longest chain with COOH; COOH carbon = **C1**; -e → **-oic acid**.' },
    { id: 'l10-k04', front: 'Formic acid', back: '**HCOOH** — fire ant stings.' },
    { id: 'l10-k05', front: 'Acetic acid', back: '**CH₃COOH** — vinegar.' },
    { id: 'l10-k06', front: 'Benzoic acid', back: '**C₆H₅COOH** — food preservative.' },
    { id: 'l10-k07', front: 'Boiling point: acids vs alcohols', back: 'Acids are **higher** — more hydrogen bonding.' },
    { id: 'l10-k08', front: 'Acid strength of RCOOH', back: '**Weak** acids — only slightly ionized (vs strong HCl, H₂SO₄).' },
    { id: 'l10-k09', front: 'RCOOH + NaOH', back: '→ **RCOO⁻Na⁺ + H₂O** (a water-soluble carboxylate salt).' },
    { id: 'l10-k10', front: 'Naming carboxylate salts', back: 'Metal + acid name with **-ic acid → -ate**: sodium acetate, potassium propanoate.' },
    { id: 'l10-k11', front: 'Soap', back: 'Salt of a long-chain carboxylic acid: **ionic (polar) head + nonpolar tail**.' },
    { id: 'l10-k12', front: 'Micelle', back: 'Sphere of soap molecules: **heads out** (water), **tails in** (trap grease).' },
    { id: 'l10-k13', front: 'How NSAIDs work', back: 'Block **prostaglandin** synthesis (aspirin, ibuprofen, naproxen).' },
    { id: 'l10-k14', front: 'α-Hydroxy acids', back: 'Skin care (glycolic, lactic acid): remove old outer skin cells.' },
    { id: 'l10-k15', front: 'Aspirin in the stomach vs intestines', back: 'Stomach (acidic): **neutral**. Intestines (basic): **ionic**. Crosses membranes in the neutral form.' },
    { id: 'l10-k16', front: 'Name this', mol: 'CC(=O)[O-].[Na+]', back: '**Sodium acetate** (sodium ethanoate).' },
  ],
  keyTerms: [
    { term: 'carboxylic acid', def: 'A compound containing a COOH (carboxyl) group.' },
    { term: 'carboxyl group', def: 'The –COOH functional group.' },
    { term: 'α carbon', def: 'The carbon bonded to the carbonyl (COOH) carbon.' },
    { term: 'carboxylate salt', def: 'The ionic product (RCOO⁻ M⁺) of a carboxylic acid and a base.' },
    { term: 'soap', def: 'A salt of a long-chain carboxylic acid.' },
    { term: 'micelle', def: 'A spherical cluster of soap molecules with ionic heads out and nonpolar tails in.' },
    { term: 'prostaglandins', def: 'Compounds that cause pain and inflammation; blocked by NSAIDs.' },
  ],
};
