// Word Splash: the chemistry words to guess. Every word comes from Lectures 1–10.
//
// ✏️ Safe to edit and extend:
//   word     4–9 letters, A–Z only (written in capitals)
//   lecture  'l01'…'l10'; section: the lesson section the "Read the notes" button opens
//   clue     shown only if she taps "Show clue" (must not contain the word itself)
//   smiles   optional structure drawn after the word is solved
// The tests check every entry. Adding words changes which word comes up on future days, but never
// a day already played (that day's word is saved with her progress).
export const WORDS = [
  // Lecture 1 — Intro to organic chemistry
  { word: 'CARBON', lecture: 'l01', section: 'what', clue: 'The element in every organic compound.' },
  { word: 'ORGANIC', lecture: 'l01', section: 'what', clue: 'Branch of chemistry that studies carbon compounds.' },
  { word: 'VALENCE', lecture: 'l01', section: 'bonding', clue: '___ electrons: the outer-shell electrons used in bonding.' },
  { word: 'COVALENT', lecture: 'l01', section: 'bonding', clue: 'A bond made by sharing electrons.' },
  { word: 'OCTET', lecture: 'l01', section: 'bonding', clue: 'A full set of eight valence electrons.' },
  { word: 'HYDROGEN', lecture: 'l01', section: 'bonding', clue: 'HONC: the atom that makes 1 bond.' },
  { word: 'OXYGEN', lecture: 'l01', section: 'bonding', clue: 'HONC: the atom that makes 2 bonds and has 2 lone pairs.' },
  { word: 'NITROGEN', lecture: 'l01', section: 'bonding', clue: 'HONC: the atom that makes 3 bonds and has 1 lone pair.' },
  { word: 'LINEAR', lecture: 'l01', section: 'shapes', clue: 'The shape with 2 groups and a 180° angle, like a C≡C carbon.' },
  { word: 'PLANAR', lecture: 'l01', section: 'shapes', clue: 'Trigonal ___: 3 groups at 120°, like a C=C carbon.' },
  { word: 'BENT', lecture: 'l01', section: 'shapes', clue: 'The shape around the O in water or an alcohol.' },
  { word: 'LONE', lecture: 'l01', section: 'shapes', clue: '___ pair: two electrons on an atom that aren\'t in a bond.' },
  { word: 'SKELETAL', lecture: 'l01', section: 'skeletal', clue: 'Line structures where every corner and end is a carbon.' },

  // Lecture 2 — Functional groups
  { word: 'ALCOHOL', lecture: 'l02', section: 'single', clue: 'Family with an –OH on a carbon.', smiles: 'CCO' },
  { word: 'ETHER', lecture: 'l02', section: 'single', clue: 'Family with an O between two carbons: C–O–C.', smiles: 'CCOCC' },
  { word: 'AMINE', lecture: 'l02', section: 'single', clue: 'Family with a nitrogen, like –NH₂, on a carbon.', smiles: 'CCN' },
  { word: 'THIOL', lecture: 'l02', section: 'single', clue: 'Family with an –SH group.', smiles: 'CCS' },
  { word: 'HALIDE', lecture: 'l02', section: 'single', clue: 'Alkyl ___: a carbon bonded to F, Cl, Br or I.', smiles: 'CCCl' },
  { word: 'HYDROXYL', lecture: 'l02', section: 'single', clue: 'The name of the –OH group.' },
  { word: 'CARBONYL', lecture: 'l02', section: 'carbonyl', clue: 'The name of the C=O group.' },
  { word: 'CARBOXYL', lecture: 'l02', section: 'carbonyl', clue: 'The name of the –COOH group.' },
  { word: 'ALDEHYDE', lecture: 'l02', section: 'carbonyl', clue: 'C=O family with at least one H on the carbonyl carbon.', smiles: 'CCC=O' },
  { word: 'KETONE', lecture: 'l02', section: 'carbonyl', clue: 'C=O family with a carbon on each side of the carbonyl.', smiles: 'CC(C)=O' },
  { word: 'ESTER', lecture: 'l02', section: 'carbonyl', clue: 'C=O family with an –OR on the carbonyl carbon (banana smell!).', smiles: 'CC(=O)OC' },
  { word: 'AMIDE', lecture: 'l02', section: 'carbonyl', clue: 'C=O family with a nitrogen on the carbonyl carbon.', smiles: 'CC(N)=O' },
  { word: 'CITRIC', lecture: 'l02', section: 'carbonyl', clue: 'The sour acid in lemons and oranges.' },
  { word: 'BENZENE', lecture: 'l02', section: 'hydrocarbons', clue: 'Six-carbon ring with three alternating double bonds.', smiles: 'c1ccccc1' },
  { word: 'AROMATIC', lecture: 'l02', section: 'hydrocarbons', clue: 'The family of compounds with a benzene ring.', smiles: 'Cc1ccccc1' },
  { word: 'POLAR', lecture: 'l02', section: 'polarity', clue: 'Having a net dipole, like water.' },
  { word: 'NONPOLAR', lecture: 'l02', section: 'polarity', clue: 'No net dipole, like an alkane.' },
  { word: 'DIPOLE', lecture: 'l02', section: 'polarity', clue: 'A separation of charge in a bond or a molecule.' },
  { word: 'LONDON', lecture: 'l02', section: 'imf', clue: '___ dispersion forces: the only attraction between alkane molecules.' },
  { word: 'SOLUBLE', lecture: 'l02', section: 'solubility', clue: 'Able to dissolve, like ethanol in water.' },
  { word: 'VITAMIN', lecture: 'l02', section: 'vitamins', clue: 'Organic compound needed in small amounts that the body can\'t make.' },
  { word: 'RETINOL', lecture: 'l02', section: 'vitamins', clue: 'The chemical name of vitamin A.' },
  { word: 'SCURVY', lecture: 'l02', section: 'vitamins', clue: 'The disease caused by too little vitamin C.' },
  { word: 'COLLAGEN', lecture: 'l02', section: 'vitamins', clue: 'Connective tissue that needs vitamin C to form.' },

  // Lecture 3 — Alkanes
  { word: 'ALKANE', lecture: 'l03', section: 'intro', clue: 'Hydrocarbon with only C–C and C–H single bonds.', smiles: 'CCCC' },
  { word: 'METHANE', lecture: 'l03', section: 'names', clue: 'CH₄, the one-carbon alkane.', smiles: 'C' },
  { word: 'ETHANE', lecture: 'l03', section: 'names', clue: 'The two-carbon alkane.', smiles: 'CC' },
  { word: 'PROPANE', lecture: 'l03', section: 'names', clue: 'The three-carbon alkane (grill fuel).', smiles: 'CCC' },
  { word: 'BUTANE', lecture: 'l03', section: 'names', clue: 'The four-carbon alkane (lighter fluid).', smiles: 'CCCC' },
  { word: 'PENTANE', lecture: 'l03', section: 'names', clue: 'The five-carbon alkane.', smiles: 'CCCCC' },
  { word: 'HEXANE', lecture: 'l03', section: 'names', clue: 'The six-carbon alkane.', smiles: 'CCCCCC' },
  { word: 'HEPTANE', lecture: 'l03', section: 'names', clue: 'The seven-carbon alkane.', smiles: 'CCCCCCC' },
  { word: 'OCTANE', lecture: 'l03', section: 'names', clue: 'The eight-carbon alkane.', smiles: 'CCCCCCCC' },
  { word: 'NONANE', lecture: 'l03', section: 'names', clue: 'The nine-carbon alkane.', smiles: 'CCCCCCCCC' },
  { word: 'DECANE', lecture: 'l03', section: 'names', clue: 'The ten-carbon alkane.', smiles: 'CCCCCCCCCC' },
  { word: 'ISOMER', lecture: 'l03', section: 'isomers', clue: 'Same molecular formula, different structure.' },
  { word: 'PRIMARY', lecture: 'l03', section: 'classify', clue: 'A 1° carbon: bonded to one other carbon.' },
  { word: 'TERTIARY', lecture: 'l03', section: 'classify', clue: 'A 3° carbon: bonded to three other carbons.' },
  { word: 'IUPAC', lecture: 'l03', section: 'iupac', clue: 'The official system for naming compounds (five letters).' },
  { word: 'PARENT', lecture: 'l03', section: 'iupac', clue: 'The longest chain gives the ___ name.' },
  { word: 'PREFIX', lecture: 'l03', section: 'iupac', clue: 'The part before the parent name, like "2-methyl".' },
  { word: 'SUFFIX', lecture: 'l03', section: 'iupac', clue: 'The name ending that tells the family, like "-ane" or "-ol".' },
  { word: 'ALKYL', lecture: 'l03', section: 'iupac', clue: 'A substituent made from an alkane, like methyl or ethyl.' },
  { word: 'METHYL', lecture: 'l03', section: 'iupac', clue: 'The –CH₃ substituent.' },
  { word: 'ETHYL', lecture: 'l03', section: 'iupac', clue: 'The –CH₂CH₃ substituent.' },
  { word: 'PROPYL', lecture: 'l03', section: 'iupac', clue: 'The straight three-carbon substituent.' },
  { word: 'BUTYL', lecture: 'l03', section: 'iupac', clue: 'A four-carbon substituent.' },
  { word: 'ISOPROPYL', lecture: 'l03', section: 'iupac', clue: 'The (CH₃)₂CH– substituent.' },
  { word: 'CYCLO', lecture: 'l03', section: 'cyclo', clue: 'The prefix for an alkane ring.', smiles: 'C1CCCCC1' },

  // Lecture 4 — Alkenes & alkynes
  { word: 'ALKENE', lecture: 'l04', section: 'intro', clue: 'Hydrocarbon with a C=C double bond.', smiles: 'CC=CC' },
  { word: 'ALKYNE', lecture: 'l04', section: 'intro', clue: 'Hydrocarbon with a C≡C triple bond.', smiles: 'CC#CC' },
  { word: 'ETHYLENE', lecture: 'l04', section: 'intro', clue: 'The common name of the simplest alkene.', smiles: 'C=C' },
  { word: 'ETHENE', lecture: 'l04', section: 'naming', clue: 'The IUPAC name of CH₂=CH₂.', smiles: 'C=C' },
  { word: 'PROPENE', lecture: 'l04', section: 'naming', clue: 'The three-carbon alkene.', smiles: 'C=CC' },
  { word: 'TRANS', lecture: 'l04', section: 'cis-trans', clue: 'Two groups on opposite sides of a C=C.', smiles: 'C/C=C/C' },
  { word: 'KINK', lecture: 'l04', section: 'fats', clue: 'What a cis double bond puts in a fatty acid chain.' },
  { word: 'FATTY', lecture: 'l04', section: 'fats', clue: '___ acids: long-chain carboxylic acids that make up fats and oils.' },
  { word: 'OLEIC', lecture: 'l04', section: 'fats', clue: 'Fatty acid with one cis C=C (olive oil).' },
  { word: 'STEARIC', lecture: 'l04', section: 'fats', clue: 'A saturated 18-carbon fatty acid.', smiles: 'CCCCCCCCCCCCCCCCCC(=O)O' },
  { word: 'SATURATED', lecture: 'l04', section: 'fats', clue: 'A fat with no C=C bonds, solid at room temperature.' },
  { word: 'MARGARINE', lecture: 'l04', section: 'fats', clue: 'Butter substitute made by partially hydrogenating vegetable oil.' },
  { word: 'ADDITION', lecture: 'l04', section: 'addition', clue: 'Reaction type where atoms add to both carbons of a C=C.' },
  { word: 'HYDRATION', lecture: 'l04', section: 'addition', clue: 'Adding H and OH across a C=C (H₂O with H₂SO₄).' },
  { word: 'CATALYST', lecture: 'l04', section: 'addition', clue: 'Pd in hydrogenation: speeds up the reaction without being used up.' },
  { word: 'BROMINE', lecture: 'l04', section: 'addition', clue: 'Br₂: adds one Br to each carbon of a C=C.' },

  // Lecture 5 — Alcohols
  { word: 'SECONDARY', lecture: 'l05', section: 'structure', clue: 'A 2° alcohol: the OH carbon is bonded to two carbons.', smiles: 'CC(O)C' },
  { word: 'ETHANOL', lecture: 'l05', section: 'interesting', clue: 'The alcohol in alcoholic drinks.', smiles: 'CCO' },
  { word: 'METHANOL', lecture: 'l05', section: 'metabolism', clue: 'The toxic one-carbon alcohol.', smiles: 'CO' },
  { word: 'PROPANOL', lecture: 'l05', section: 'naming', clue: 'The three-carbon alcohol (1- or 2-___).', smiles: 'CCCO' },
  { word: 'RUBBING', lecture: 'l05', section: 'interesting', clue: '___ alcohol: 2-propanol, used on skin and instruments.' },
  { word: 'GLYCOL', lecture: 'l05', section: 'interesting', clue: 'Ethylene ___: the sweet, very toxic diol in antifreeze.', smiles: 'OCCO' },
  { word: 'GLYCEROL', lecture: 'l05', section: 'interesting', clue: 'Sweet, nontoxic triol used in lotions and soap.', smiles: 'OCC(O)CO' },
  { word: 'DIOL', lecture: 'l05', section: 'naming', clue: 'An alcohol with two OH groups.' },
  { word: 'TRIOL', lecture: 'l05', section: 'naming', clue: 'An alcohol with three OH groups.' },
  { word: 'FERMENT', lecture: 'l05', section: 'interesting', clue: 'What yeast does to carbohydrates to make ethanol.' },
  { word: 'STARCH', lecture: 'l05', section: 'interesting', clue: 'Plant carbohydrate that humans digest into glucose.' },
  { word: 'CELLULOSE', lecture: 'l05', section: 'interesting', clue: 'Plant carbohydrate in wood and cotton that humans can\'t digest.' },
  { word: 'GLUCOSE', lecture: 'l05', section: 'interesting', clue: 'The sugar with five OH groups in its open-chain form.' },
  { word: 'ZAITSEV', lecture: 'l05', section: 'dehydration', clue: 'Rule: the major alkene has more carbon groups on the C=C.' },
  { word: 'OXIDATION', lecture: 'l05', section: 'oxidation', clue: 'More C–O bonds or fewer C–H bonds. Shown as [O].' },

  // Lecture 6 — Ethers, halides & thiols
  { word: 'EPOXIDE', lecture: 'l06', section: 'ethers', clue: 'A three-membered ring ether.', smiles: 'C1CO1' },
  { word: 'HALOGEN', lecture: 'l06', section: 'halides', clue: 'F, Cl, Br or I.' },
  { word: 'CHLORO', lecture: 'l06', section: 'halides', clue: 'The prefix for a Cl substituent.', smiles: 'CCCl' },
  { word: 'BROMO', lecture: 'l06', section: 'halides', clue: 'The prefix for a Br substituent.', smiles: 'CCBr' },
  { word: 'SULFUR', lecture: 'l06', section: 'thiols', clue: 'The element in a thiol\'s –SH group.' },
  { word: 'SKUNK', lecture: 'l06', section: 'thiols', clue: 'The animal whose spray gets its smell from thiols.' },
  { word: 'PERM', lecture: 'l06', section: 'thiols', clue: 'Hair treatment that breaks and re-forms disulfide bonds.' },
  { word: 'DISULFIDE', lecture: 'l06', section: 'thiols', clue: 'R–S–S–R, made by oxidizing two thiols.', smiles: 'CCSSCC' },

  // Lecture 7 — Chirality
  { word: 'CHIRAL', lecture: 'l07', section: 'chiral', clue: 'Not superimposable on its mirror image.', smiles: 'CC(O)CC' },
  { word: 'ACHIRAL', lecture: 'l07', section: 'chiral', clue: 'Superimposable on its mirror image.' },
  { word: 'MIRROR', lecture: 'l07', section: 'chiral', clue: 'Enantiomers are ___ images that don\'t line up.' },
  { word: 'HANDS', lecture: 'l07', section: 'chiral', clue: 'The classic chiral objects: your left and right ___.' },
  { word: 'CENTER', lecture: 'l07', section: 'centers', clue: 'A carbon with four different groups is a chirality ___.' },
  { word: 'RACEMIC', lecture: 'l07', section: 'drugs', clue: 'A 50:50 mixture of two enantiomers.' },
  { word: 'NAPROXEN', lecture: 'l07', section: 'drugs', clue: 'Pain reliever (Aleve) sold as only one enantiomer.', smiles: 'COc1ccc2cc(ccc2c1)C(C)C(=O)O' },

  // Lecture 8 — Aldehydes & ketones
  { word: 'ACETONE', lecture: 'l08', section: 'interesting', clue: 'The simplest ketone, in nail polish remover.', smiles: 'CC(C)=O' },
  { word: 'FORMALIN', lecture: 'l08', section: 'interesting', clue: 'Formaldehyde in water, used to preserve specimens.' },
  { word: 'VANILLIN', lecture: 'l08', section: 'interesting', clue: 'The aldehyde that tastes like vanilla.', smiles: 'COc1cc(C=O)ccc1O' },
  { word: 'CINNAMON', lecture: 'l08', section: 'interesting', clue: 'The spice whose flavor is an aldehyde.' },
  { word: 'METHANAL', lecture: 'l08', section: 'naming', clue: 'The IUPAC name of formaldehyde.', smiles: 'C=O' },
  { word: 'ETHANAL', lecture: 'l08', section: 'naming', clue: 'The IUPAC name of acetaldehyde.', smiles: 'CC=O' },
  { word: 'PROPANAL', lecture: 'l08', section: 'naming', clue: 'The three-carbon aldehyde.', smiles: 'CCC=O' },
  { word: 'BUTANONE', lecture: 'l08', section: 'naming', clue: 'The four-carbon ketone.', smiles: 'CCC(C)=O' },
  { word: 'NADH', lecture: 'l08', section: 'reduction', clue: 'The coenzyme cells use as a reducing agent.' },
  { word: 'REDUCTION', lecture: 'l08', section: 'reduction', clue: 'Fewer C–O bonds or more C–H bonds: the reverse of oxidation.' },

  // Lecture 9 — Acids & bases
  { word: 'ACID', lecture: 'l09', section: 'definitions', clue: 'Brønsted–Lowry: a proton (H⁺) donor.' },
  { word: 'BASE', lecture: 'l09', section: 'definitions', clue: 'Brønsted–Lowry: a proton (H⁺) acceptor.' },
  { word: 'PROTON', lecture: 'l09', section: 'definitions', clue: 'H⁺: what an acid gives away.' },
  { word: 'DONOR', lecture: 'l09', section: 'definitions', clue: 'An acid is a proton ___.' },
  { word: 'ACCEPTOR', lecture: 'l09', section: 'definitions', clue: 'A base is a proton ___.' },
  { word: 'BRONSTED', lecture: 'l09', section: 'definitions', clue: '___–Lowry: the acid–base definition from class.' },
  { word: 'LOWRY', lecture: 'l09', section: 'definitions', clue: 'Brønsted–___: the acid–base definition from class.' },
  { word: 'CONJUGATE', lecture: 'l09', section: 'conjugates', clue: '___ base: what\'s left after an acid donates H⁺.' },
  { word: 'HYDRONIUM', lecture: 'l09', section: 'ph', clue: 'H₃O⁺.' },
  { word: 'NEUTRAL', lecture: 'l09', section: 'ph', clue: 'pH exactly 7.' },
  { word: 'ACIDIC', lecture: 'l09', section: 'ph', clue: 'pH below 7.' },
  { word: 'BASIC', lecture: 'l09', section: 'ph', clue: 'pH above 7.' },
  { word: 'AMMONIA', lecture: 'l09', section: 'ph', clue: 'Household cleaner with a pH of about 11.' },
  { word: 'BLEACH', lecture: 'l09', section: 'ph', clue: 'Household product with a pH of about 12.5.' },
  { word: 'BUFFER', lecture: 'l09', section: 'buffers', clue: 'A weak acid plus its conjugate base: resists changes in pH.' },
  { word: 'CARBONIC', lecture: 'l09', section: 'blood', clue: '___ acid, H₂CO₃: half of the blood\'s main buffer.' },
  { word: 'ACIDOSIS', lecture: 'l09', section: 'blood', clue: 'Blood pH below 7.35.' },
  { word: 'ALKALOSIS', lecture: 'l09', section: 'blood', clue: 'Blood pH above 7.45.' },

  // Lecture 10 — Carboxylic acids
  { word: 'ACETIC', lecture: 'l10', section: 'naming', clue: 'The acid in vinegar.', smiles: 'CC(=O)O' },
  { word: 'FORMIC', lecture: 'l10', section: 'naming', clue: 'The one-carbon carboxylic acid (what the liver makes from methanol).', smiles: 'OC=O' },
  { word: 'BUTANOIC', lecture: 'l10', section: 'naming', clue: 'The four-carbon carboxylic acid.', smiles: 'CCCC(=O)O' },
  { word: 'BENZOIC', lecture: 'l10', section: 'naming', clue: 'A carboxylic acid on a benzene ring.', smiles: 'OC(=O)c1ccccc1' },
  { word: 'LACTIC', lecture: 'l10', section: 'health', clue: 'An α-hydroxy acid in skin care (also made by tired muscles).', smiles: 'CC(O)C(=O)O' },
  { word: 'GLYCOLIC', lecture: 'l10', section: 'health', clue: 'The simplest α-hydroxy acid, used in skin care.', smiles: 'OCC(=O)O' },
  { word: 'NSAID', lecture: 'l10', section: 'health', clue: 'The drug class of aspirin, ibuprofen and naproxen (five letters).' },
  { word: 'ASPIRIN', lecture: 'l10', section: 'aspirin', clue: 'Pain reliever that stays neutral in the stomach and ionizes in the intestines.', smiles: 'CC(=O)Oc1ccccc1C(=O)O' },
  { word: 'SODIUM', lecture: 'l10', section: 'acidity', clue: 'The metal named first in "___ acetate".' },
  { word: 'SOAP', lecture: 'l10', section: 'soap', clue: 'The sodium salt of a long-chain carboxylic acid.', smiles: 'CCCCCCCCCCCCCCCCCC(=O)[O-].[Na+]' },
  { word: 'MICELLE', lecture: 'l10', section: 'soap', clue: 'A sphere of soap molecules surrounding grease.' },
];
